"""Internal policy tables for root API convergence."""

DEPRECATED_INTERNAL_ROOT_EXPORTS = {
    "DistributedEvidenceContract",
    "DistributedTransportEvidence",
    "JAXDistributedQuantumPlan",
    "JAXMPSRankShardState",
    "JAXStatevectorShardState",
    "JAXTNSliceRankState",
    "StatevectorShard",
    "StatevectorShardState",
}

MIGRATED_ROOT_EXPORTS = {
    "GateInfo": "flagquantum.operators.GateInfo",
    "HybridParallelPlan": "flagquantum.runtime.parallel.HybridParallelPlan",
    "MPSAcceptanceGates": "flagquantum.runtime.backends.mps.MPSAcceptanceGates",
    "MPSCrossoverMeasurement": "flagquantum.runtime.backends.mps.MPSCrossoverMeasurement",
    "MPSProductionAcceptanceError": "flagquantum.runtime.backends.mps.MPSProductionAcceptanceError",
    "MPSProductionPlan": "flagquantum.runtime.backends.mps.MPSProductionPlan",
    "MPSProductionSupport": "flagquantum.runtime.backends.mps.MPSProductionSupport",
    "MPSReverseCheckpointPolicy": "flagquantum.runtime.backends.mps.records.MPSReverseCheckpointPolicy",
    "NoiseModel": "flagquantum.noise.NoiseModel",
    "PauliMeasurementPlan": "flagquantum.deployment.PauliMeasurementPlan",
    "PrecisionPolicy": "flagquantum.training.PrecisionPolicy",
    "PrecisionPolicyError": "flagquantum.training.PrecisionPolicyError",
    "SeedContract": "flagquantum.training.SeedContract",
    "build_mps_release_artifact": "flagquantum.runtime.backends.mps.build_mps_release_artifact",
    "compile_for_backend": "flagquantum.compiler.compile_for_backend",
    "create_deployment_package": "flagquantum.deployment.create_deployment_package",
    "create_pauli_measurement_plan": "flagquantum.deployment.create_pauli_measurement_plan",
    "deploy_circuit": "flagquantum.deployment.deploy_circuit",
    "distributed_tensor_network_amplitude": "flagquantum.runtime.distributed.tensor_network_execution.distributed_tensor_network_amplitude",
    "distributed_tensor_network_amplitudes": "flagquantum.runtime.distributed.tensor_network_execution.distributed_tensor_network_amplitudes",
    "distributed_tensor_network_expectation": "flagquantum.runtime.distributed.tensor_network_execution.distributed_tensor_network_expectation",
    "distributed_tensor_network_expectations": "flagquantum.runtime.distributed.tensor_network_execution.distributed_tensor_network_expectations",
    "gate_info": "flagquantum.operators.gate_info",
    "hamiltonian_expectation_from_grouped_counts": "flagquantum.deployment.hamiltonian_expectation_from_grouped_counts",
    "noisy_density_matrix": "flagquantum.noise.noisy_density_matrix",
    "plan_production_mps": "flagquantum.runtime.backends.mps.plan_production_mps",
    "plan_runtime_selection": "flagquantum.runtime.planner.plan_runtime_selection",
    "resolve_device": "flagquantum.backends.resolve_device",
    "run_mps": "flagquantum.backends.run_mps",
    "run_native": "flagquantum.backends.run_native",
    "run_noisy_mps": "flagquantum.backends.run_noisy_mps",
    "run_target": "flagquantum.backends.run_target",
    "run_tensor_network": "flagquantum.backends.run_tensor_network",
    "select_backend_by_cost": "flagquantum.runtime.planner.select_backend_by_cost",
    "tensor_network_amplitude": "flagquantum.backends.tensor_network.tensor_network_amplitude",
    "tensor_network_amplitudes": "flagquantum.backends.tensor_network.tensor_network_amplitudes",
    "tensor_network_expectations": "flagquantum.backends.tensor_network.tensor_network_expectations",
    "TopologyMismatchError": "flagquantum.training.TopologyMismatchError",
    "TrainingStateError": "flagquantum.training.TrainingStateError",
    "train_distributed_mps": "flagquantum.experimental.distributed.train_distributed_mps",
    "train_distributed_statevector": "flagquantum.experimental.distributed.train_distributed_statevector",
    "validate_production_mps_workload": "flagquantum.runtime.backends.mps.validate_production_mps_workload",
    "NonFiniteTrainingError": "flagquantum.training.NonFiniteTrainingError",
    "seed_everything": "flagquantum.training.seed_everything",
}

REMOVED_ROOT_EXPORTS = {
    "get_version": "flagquantum.__version__",
    "hello": None,
    "info": None,
    "assert_finite_training": "Module.execute(..., correctness_debug=True)",
    "load_training_checkpoint": "Module.load_checkpoint(...) or an application-owned checkpoint loop",
    "save_training_checkpoint": "Module.save_checkpoint(...) or an application-owned checkpoint loop",
}
