"""Unit coverage for the dynamic-code record and the ring schedule.

The code records in this package state a code as one group: ``StabilizerCode`` and
``CssCode`` state their checks and the group is what they stabilize in every round.
This file pins the record whose code *is* a sequence of groups -- a dynamic code,
stated as a period of measurement phases, whose instantaneous stabilizer group
changes from round to round while the information it protects does not.

Two rules carry the record, and both are proved here rather than asserted. The
first is that the group a round stabilizes is the part of the previous round's
group that commutes with every measured operator, computed by solving one linear
equation per measured operator in the old group's coordinates. The tempting
shortcut -- testing the old group's generators one at a time -- is wrong, and
``test_the_basis_wise_reading_would_lose_a_product`` exhibits the smallest witness
of the difference instead of taking the rule on trust. The second is that the
period's two numbers are read at every round of it, which
``test_every_ring_schedule_settles_with_one_count_per_period`` measures over the
whole ring family.

What this file proves
---------------------

1. ``test_the_ring_derives_its_arithmetic_from_the_width``: the two-phase ring on
   ``n`` wires settles at period two after one transient round, holds ``n / 2 + 1``
   checks, protects ``n / 2 - 1`` qubits, and has least logical weight two -- all
   five numbers derived from the schedule rather than stated next to it.
2. ``test_the_ring_rounds_measure_the_two_edge_classes_of_one_ring``: the first
   round measures ``Z`` on the even edges and the second ``X`` on the odd ones, the
   two classes partition the ring's edges, and each round's operators are disjoint.
3. ``test_the_advance_solves_for_the_surviving_subgroup``: for random small
   schedules, the group a round advances to is exactly the elements of the old group
   that commute with the round's measurements, plus the measurements themselves,
   compared against a brute-force walk of every element of the old group.
4. ``test_the_basis_wise_reading_would_lose_a_product``: the group generated by
   ``Z0 Z1`` and ``Z0 Z2`` measured against ``X0`` keeps the product ``Z1 Z2`` and
   neither generator, so a generator-at-a-time reading reports the trivial group
   where the solved reading reports a rank-one group.
5. ``test_every_ring_schedule_settles_with_one_count_per_period``: every ring
   schedule of two, three and four phase classes over widths four to twelve settles,
   protects at least one qubit, and has every round of its period protecting the same
   number, with no least logical weight above two.
6. ``test_the_period_is_the_least_number_the_groups_repeat_over``: two phases that
   measure the same operators under different names repeat over two rounds and not
   over four, so the period is a property of the groups and not of the phase count.
7. ``test_the_least_logical_weight_is_the_lightest_round_of_the_period``: a period
   whose two rounds read one and two reports one, and reports it at the round that
   read it -- a claim about a period has to hold where the period is weakest.
8. ``test_the_search_skips_the_candidates_that_are_already_checks``: a group whose
   lightest generator weighs one reports a least logical weight of two, because the
   weight-one operator that commutes with the group is the check itself; the only
   weight-one operator that commutes with the group is measured to be that check, so
   the search has to skip it rather than report it.
9. ``test_the_four_phase_ring_is_refused_and_the_two_phase_ring_is_not``: measuring
   the two edge classes in the other order settles at a group of full rank, which
   protects nothing and is refused by name, while the same width's two-phase ring is
   accepted -- so the refusal is about the schedule rather than about the letters.
10. ``test_the_record_refuses_a_budget_it_did_not_settle_within``: a schedule that has
    not repeated inside its budget is refused rather than reported with a count read
    off a group that is still moving.
11. ``test_the_record_refuses_a_search_bound_it_could_not_reach``: the same ring with
    a search bound of one has no logical operator to report and is refused; with a
    bound of two it reports two. A least weight the search did not reach is not a
    distance.
12. ``test_the_record_refuses_malformed_schedules``: fifteen malformed records and
    phases are refused, each for a named reason.
13. ``test_the_logical_operators_are_operators_of_the_reading_round``: every reported
    logical operator commutes with every generator of the reading round, lies outside
    their span, and the lightest of them weighs what the record says.
14. ``test_the_public_namespace_publishes_the_record``: the three names are exported
    from the package root and named in its ``__all__``.

The one refusal this file cannot reach is the count-agreement check in the
derivation: it fires only on a settled period whose rounds protect different numbers
of qubits, and no such period has been found. At width three every two-round
schedule was walked -- 14,768,649 of them -- and every cycle of the advance map had
one rank, as did a further two million sampled three- and four-round schedules at the
same width, seven hundred thousand random schedules over widths three to seven, and
every schedule of the ring family. The check is kept because a period is only a code
if its count is one number, and a settled period that disagreed would otherwise be
reported with an arbitrary one of its rounds' counts.
"""

from __future__ import annotations

import itertools

import pytest

from flagquantum.qec.floquet import (
    FloquetCode,
    MeasurementPhase,
    _advance,
    _combination,
    _commutes,
    _least_logical_weight,
    _phase_rows,
    _surviving,
    ring_floquet_code,
)
from flagquantum.qec.gf2 import in_span, rank, reduce_rows
from flagquantum.qec.pauli import Pauli

pytestmark = pytest.mark.unit

RING_WIDTHS = (4, 6, 8, 10, 12)


def _ring_schedule(width: int, kinds: str) -> tuple[MeasurementPhase, ...]:
    """The ring's edges split by index modulo ``len(kinds)``, one family per class."""

    classes = len(kinds)
    assert classes <= width
    edges = [(wire, (wire + 1) % width) for wire in range(width)]
    phases = []
    for offset, kind in enumerate(kinds):
        operators = []
        for index in range(width):
            if index % classes != offset:
                continue
            wires = tuple(sorted(edges[index]))
            if kind == "X":
                operators.append(Pauli(x_wires=wires))
            elif kind == "Z":
                operators.append(Pauli(z_wires=wires))
            else:
                operators.append(Pauli(x_wires=wires, z_wires=wires))
        phases.append(
            MeasurementPhase(name=f"class-{offset}", operators=tuple(operators))
        )
    return tuple(phases)


def _rows(operators: tuple[Pauli, ...], width: int) -> list[int]:
    """Return Paulis as symplectic rows, so a test can read a group's rank."""

    return [
        _phase_rows(MeasurementPhase("rows", (operator,)), width)[0]
        for operator in operators
    ]


def _two_phase_ring(width: int) -> FloquetCode:
    return ring_floquet_code(width)


def test_the_ring_derives_its_arithmetic_from_the_width() -> None:
    for width in RING_WIDTHS:
        ring = _two_phase_ring(width)

        assert ring.num_data_qubits == width
        assert ring.data_wires == tuple(range(width))
        assert ring.num_phases == 2
        assert ring.period == 2
        assert ring.num_transient_rounds == 1

        # The first round leaves one check per edge; the second keeps a single one of
        # them beside its own measurements, so the held group has n / 2 + 1 generators.
        assert ring.num_stabilizer_generators == width // 2 + 1
        assert ring.num_logical_qubits == width // 2 - 1
        assert ring.least_logical_weight == 2

        # Representatives come in pairs, one per family, so there are twice as many
        # of them as there are protected qubits.
        assert len(ring.logical_operators) == 2 * ring.num_logical_qubits
        assert len(ring.steady_stabilizer_groups()) == ring.period


def test_the_ring_rounds_measure_the_two_edge_classes_of_one_ring() -> None:
    width = 8
    ring = _two_phase_ring(width)
    even_edges = {(0, 1), (2, 3), (4, 5), (6, 7)}
    odd_edges = {(1, 2), (3, 4), (5, 6), (0, 7)}

    assert [phase.name for phase in ring.phases] == ["even-edges-z", "odd-edges-x"]

    z_round, x_round = ring.phases
    assert {operator.to_text() for operator in z_round.operators} == {
        f"Z{left}*Z{right}" for left, right in sorted(even_edges)
    }
    assert {operator.to_text() for operator in x_round.operators} == {
        f"X{min(left, right)}*X{max(left, right)}" for left, right in sorted(odd_edges)
    }
    assert z_round.num_operators == x_round.num_operators == width // 2
    assert z_round.num_independent_operators == x_round.num_independent_operators
    assert even_edges | odd_edges == {
        (min(wire, (wire + 1) % width), max(wire, (wire + 1) % width))
        for wire in range(width)
    }

    # Each round's supports are disjoint, and the closing edge names its wires in
    # ascending order rather than in the order the ring visits them.
    for phase in ring.phases:
        touched = [wire for operator in phase.operators for wire in operator.support]
        assert sorted(touched) == list(range(width))
    assert (0, 7) in {tuple(operator.support) for operator in x_round.operators}


def test_the_advance_solves_for_the_surviving_subgroup() -> None:
    schedules = (
        (4, ("Z", "X")),
        (4, ("X", "Y")),
        (6, ("Y", "Z")),
        (6, ("X", "Z", "Y")),
        (4, ("Z", "X", "Z", "X")),
    )
    for width, kinds in schedules:
        phases = _ring_schedule(width, kinds)
        rows_of = [_phase_rows(phase, width) for phase in phases]
        group = reduce_rows(rows_of[0])
        for index in range(1, 4 * len(rows_of)):
            measured = rows_of[index % len(rows_of)]
            advanced = _advance(group, measured, width)

            # The brute force: walk every element of the old group, keep the ones
            # that commute with every measured operator, and add the measurements.
            survivors = [
                _combination(list(group), coefficients)
                for coefficients in range(1 << len(group))
                if all(
                    _commutes(_combination(list(group), coefficients), other, width)
                    for other in measured
                )
            ]
            expected = reduce_rows(survivors + list(measured))

            assert rank(advanced) == rank(expected)
            for row in advanced:
                assert in_span(row, list(expected))
            for row in expected:
                assert in_span(row, list(advanced))

            group = advanced


def test_the_basis_wise_reading_would_lose_a_product() -> None:
    width = 3
    generators = (Pauli(z_wires=(0, 1)), Pauli(z_wires=(0, 2)))
    measured = Pauli(x_wires=(0,))
    group = reduce_rows(
        [
            _phase_rows(MeasurementPhase("g", (operator,)), width)[0]
            for operator in generators
        ]
    )
    measured_rows = _phase_rows(MeasurementPhase("m", (measured,)), width)

    assert rank(group) == 2
    # Neither generator commutes with the measurement, so a generator-at-a-time
    # reading keeps nothing at all.
    assert not any(_commutes(row, measured_rows[0], width) for row in group)

    # Their product does commute, and the solved reading keeps it.
    product = _combination(list(group), 0b11)
    assert _commutes(product, measured_rows[0], width)
    solved = _surviving(group, measured_rows, width)
    by_basis = reduce_rows(
        [row for row in group if _commutes(row, measured_rows[0], width)]
    )
    assert rank(solved) == 1
    assert rank(by_basis) == 0
    assert in_span(product, list(solved))

    # The difference survives into the round: the advanced group holds the product
    # and the measured operator, where the shortcut's group holds only the latter.
    advanced = reduce_rows(list(solved) + measured_rows)
    naive = reduce_rows(list(by_basis) + measured_rows)
    assert rank(advanced) == 2
    assert rank(naive) == 1
    assert in_span(measured_rows[0], list(advanced))


def test_every_ring_schedule_settles_with_one_count_per_period() -> None:
    settled = 0
    weights: set[int] = set()
    for width in RING_WIDTHS:
        for classes in (2, 3, 4):
            if classes > width:
                continue
            for kinds in itertools.product("XYZ", repeat=classes):
                record = FloquetCode(
                    name=f"ring-{width}-{classes}-{''.join(kinds)}",
                    num_qubits=width,
                    phases=_ring_schedule(width, "".join(kinds)),
                )
                settled += 1

                groups = record._steady_groups
                assert len(groups) == record.period
                assert len({width - rank(group) for group in groups}) == 1
                assert record.num_logical_qubits >= 1
                assert record.least_logical_weight >= 1
                weights.add(record.least_logical_weight)

    assert settled == 585
    # No ring schedule in the family beats weight two, and the three- and four-class
    # rings reach weight one.
    assert max(weights) == 2
    assert 1 in weights
    assert _two_phase_ring(6).least_logical_weight == 2


def test_the_period_is_the_least_number_the_groups_repeat_over() -> None:
    width = 6
    phases = (
        MeasurementPhase("z-first", _two_phase_ring(width).phases[0].operators),
        MeasurementPhase("x-first", _two_phase_ring(width).phases[1].operators),
        MeasurementPhase("z-again", _two_phase_ring(width).phases[0].operators),
        MeasurementPhase("x-again", _two_phase_ring(width).phases[1].operators),
    )
    repeated = FloquetCode(name="ring stated twice", num_qubits=width, phases=phases)

    # Four phases, two rounds: the period is read off the groups and not the count.
    assert repeated.num_phases == 4
    assert repeated.period == 2
    assert len(repeated.steady_stabilizer_groups()) == 2

    # And the group sequence really does repeat over two: the two steady rounds are
    # the same pair the two-phase ring settles into.
    assert repeated.num_logical_qubits == _two_phase_ring(width).num_logical_qubits
    assert repeated.least_logical_weight == _two_phase_ring(width).least_logical_weight


def test_the_least_logical_weight_is_the_lightest_round_of_the_period() -> None:
    width = 3
    phases = (
        MeasurementPhase(
            "two-checks", (Pauli.from_text("Z0*Y1"), Pauli.from_text("X0*X1*X2"))
        ),
        MeasurementPhase("one-check", (Pauli.from_text("Y0*Y1*Y2"),)),
    )
    record = FloquetCode(name="an uneven period", num_qubits=width, phases=phases)

    assert record.period == 2
    assert record.num_transient_rounds == 0
    assert record.num_logical_qubits == 1

    # The two rounds of the period do not read alike: the first one's lightest logical
    # operator weighs one and the second one's weighs two.
    steady = record.steady_stabilizer_groups()
    assert len(steady) == 2
    readings = [
        _least_logical_weight(
            width=width,
            group=tuple(_rows(group, width)),
            bound=record.distance_search_weight,
        )
        for group in steady
    ]
    assert sorted(readings) == [1, 2]

    # The record reports the lighter of the two, and it reports it at the round that
    # read it, because a claim about a period has to hold where the period is weakest.
    assert record.least_logical_weight == 1
    lightest = steady[readings.index(1)]
    assert {operator.to_text() for operator in record.stabilizer_generators} == {
        operator.to_text() for operator in lightest
    }


def test_the_search_skips_the_candidates_that_are_already_checks() -> None:
    width = 3
    phases = (
        MeasurementPhase(
            "a light check and a pair",
            (Pauli.from_text("X0"), Pauli.from_text("Y1*Y2")),
        ),
    )
    record = FloquetCode(name="a check of weight one", num_qubits=width, phases=phases)

    assert record.period == 1
    assert record.num_transient_rounds == 0
    assert record.num_logical_qubits == 1

    # The group holds a weight-one element, so its lightest generator weighs one while
    # its least logical operator weighs two.
    generators = record.stabilizer_generators
    assert min(operator.weight for operator in generators) == 1
    assert "X0" in {operator.to_text() for operator in generators}
    assert record.least_logical_weight == 2

    # Weight one really is exhausted: the only weight-one operator that commutes with
    # the group is ``X0`` itself, which is why the search has to skip what is already
    # in the group rather than report it as the least logical operator.
    singles = [Pauli(x_wires=(wire,)) for wire in range(width)]
    singles += [Pauli(z_wires=(wire,)) for wire in range(width)]
    commuting = [
        operator
        for operator in singles
        if all(operator.commutes_with(generator) for generator in generators)
    ]
    assert [operator.to_text() for operator in commuting] == ["X0"]
    assert in_span(_rows(commuting, width)[0], list(_rows(generators, width)))


def test_the_four_phase_ring_is_refused_and_the_two_phase_ring_is_not() -> None:
    for width in (4, 6, 8):
        # The two edge classes in the other order: Z even, X odd, Z odd, X even.
        first, second = _ring_schedule(width, "ZX")
        phases = (
            MeasurementPhase("a", first.operators),
            MeasurementPhase("b", second.operators),
            MeasurementPhase("c", _ring_schedule(width, "XZ")[1].operators),
            MeasurementPhase("d", _ring_schedule(width, "XZ")[0].operators),
        )
        with pytest.raises(ValueError, match="protects no qubit"):
            FloquetCode(name="four-phase ring", num_qubits=width, phases=phases)

        # The control: the same width, the same letters, accepted.
        assert _two_phase_ring(width).num_logical_qubits == width // 2 - 1


def test_the_record_refuses_a_budget_it_did_not_settle_within() -> None:
    ring = _two_phase_ring(6)
    with pytest.raises(ValueError, match="has not settled inside 1 rounds"):
        FloquetCode(
            name="ring under a one-round budget",
            num_qubits=6,
            phases=ring.phases,
            max_rounds=1,
        )


def test_the_record_refuses_a_search_bound_it_could_not_reach() -> None:
    ring = _two_phase_ring(6)
    with pytest.raises(ValueError, match="above the search bound"):
        FloquetCode(
            name="ring with a one-weight search",
            num_qubits=6,
            phases=ring.phases,
            distance_search_weight=1,
        )

    widened = FloquetCode(
        name="ring with a two-weight search",
        num_qubits=6,
        phases=ring.phases,
        distance_search_weight=2,
    )
    assert widened.least_logical_weight == 2
    assert widened.num_logical_qubits == ring.num_logical_qubits


def test_the_record_refuses_malformed_schedules() -> None:
    ring = _two_phase_ring(6)

    with pytest.raises(ValueError, match="must be named"):
        FloquetCode(name="  ", num_qubits=6, phases=ring.phases)
    with pytest.raises(ValueError, match="has no measurement phase"):
        FloquetCode(name="empty", num_qubits=6, phases=())
    with pytest.raises(ValueError, match="names one phase twice"):
        FloquetCode(
            name="twice",
            num_qubits=6,
            phases=(ring.phases[0], ring.phases[0]),
        )
    with pytest.raises(TypeError, match="not a MeasurementPhase"):
        FloquetCode(
            name="not a phase",
            num_qubits=6,
            phases=(ring.phases[0], "odd-edges-x"),
        )
    with pytest.raises(ValueError, match="outside the stated width"):
        FloquetCode(
            name="too wide",
            num_qubits=4,
            phases=(MeasurementPhase("six", ring.phases[0].operators),),
        )
    with pytest.raises(ValueError, match="is 0, and it is at least one"):
        FloquetCode(name="no wires", num_qubits=0, phases=ring.phases)
    with pytest.raises(ValueError, match="max_rounds is 0"):
        FloquetCode(name="no budget", num_qubits=6, phases=ring.phases, max_rounds=0)
    with pytest.raises(ValueError, match="distance_search_weight is 0"):
        FloquetCode(
            name="no search",
            num_qubits=6,
            phases=ring.phases,
            distance_search_weight=0,
        )
    with pytest.raises(TypeError, match="num_qubits must be an integer"):
        FloquetCode(name="true", num_qubits=True, phases=ring.phases)

    with pytest.raises(ValueError, match="must be named"):
        MeasurementPhase(name="", operators=(Pauli(z_wires=(0, 1)),))
    with pytest.raises(ValueError, match="measures no operator"):
        MeasurementPhase(name="empty", operators=())
    with pytest.raises(TypeError, match="is not a Pauli"):
        MeasurementPhase(name="text", operators=("Z0",))
    with pytest.raises(ValueError, match="is the identity"):
        MeasurementPhase(name="trivial", operators=(Pauli(),))
    with pytest.raises(ValueError, match="anticommute"):
        MeasurementPhase(
            name="ordered",
            operators=(Pauli(z_wires=(0, 1)), Pauli(x_wires=(0,))),
        )

    with pytest.raises(ValueError, match="needs an even number"):
        ring_floquet_code(5)
    with pytest.raises(ValueError, match="one edge per class"):
        ring_floquet_code(2)


def test_the_logical_operators_are_operators_of_the_reading_round() -> None:
    for width in RING_WIDTHS:
        ring = _two_phase_ring(width)
        generators = [
            _phase_rows(MeasurementPhase("g", (operator,)), width)[0]
            for operator in ring.stabilizer_generators
        ]
        reading = reduce_rows(generators)

        for operator in ring.logical_operators:
            row = _phase_rows(MeasurementPhase("l", (operator,)), width)[0]
            assert not in_span(row, list(reading))
            for generator in ring.stabilizer_generators:
                assert operator.commutes_with(generator)

        weights = [operator.weight for operator in ring.logical_operators]
        assert min(weights) == ring.least_logical_weight == 2
        assert all(weight >= ring.least_logical_weight for weight in weights)

        # Every round of the period is a code with the same count, which is what makes
        # the reported count a property of the period rather than of one round.
        for group in ring.steady_stabilizer_groups():
            elements = [
                _phase_rows(MeasurementPhase("g", (operator,)), width)[0]
                for operator in group
            ]
            assert len(elements) == ring.num_stabilizer_generators
            assert width - rank(elements) == ring.num_logical_qubits


def test_the_public_namespace_publishes_the_record() -> None:
    import flagquantum.qec as qec

    assert qec.FloquetCode is FloquetCode
    assert qec.MeasurementPhase is MeasurementPhase
    assert qec.ring_floquet_code is ring_floquet_code
    for name in ("FloquetCode", "MeasurementPhase", "ring_floquet_code"):
        assert name in qec.__all__
