"""Test and benchmark evidence associated with kernel implementations."""

from __future__ import annotations

from .schema import KernelEvidence


def _evidence(
    implementation_id: str,
    *correctness_tests: str,
    gradient_tests: tuple[str, ...] = (),
    capability_tests: tuple[str, ...] = (),
    benchmark_artifacts: tuple[str, ...] = (),
) -> KernelEvidence:
    return KernelEvidence(
        evidence_id=implementation_id.replace("FQKI-", "FQKE-", 1),
        implementation_id=implementation_id,
        correctness_tests=correctness_tests,
        gradient_tests=gradient_tests,
        capability_tests=capability_tests,
        benchmark_artifacts=benchmark_artifacts,
    )


EVIDENCE: tuple[KernelEvidence, ...] = (
    _evidence(
        "FQKI-TRITON-SV-001-A",
        "tests/unit/test_statevector_triton.py::test_generic_local_1q_matches_pytorch",
    ),
    _evidence(
        "FQKI-TRITON-SV-001-B",
        "tests/test_statevector_triton_gates.py::test_generic_constant_single_qubit_regions_preserve_input_gradient",
        gradient_tests=(
            "tests/unit/test_statevector_gate_autograd_boundary.py::test_matrix_wrapper_preserves_state_and_matrix_gradients",
        ),
    ),
    _evidence(
        "FQKI-TRITON-SV-002-A",
        "tests/test_statevector_triton_gates.py::test_local_cx_inplace_matches_index_reference",
    ),
    _evidence(
        "FQKI-TRITON-SV-003-A",
        "tests/test_statevector_triton_gates.py::test_local_cx_segment_matches_reverse_source_permutation",
    ),
    _evidence(
        "FQKI-TRITON-SV-003-B",
        "tests/test_statevector_triton_gates.py::test_constant_ry_rz_triton_path_with_cx_matches_cpu",
        gradient_tests=(
            "tests/unit/test_statevector_gate_autograd_boundary.py::test_cx_wrapper_reverses_noncommuting_gate_sequence",
        ),
    ),
    _evidence(
        "FQKI-TRITON-SV-004-A",
        "tests/test_statevector_triton_gates.py::test_constant_ry_rz_triton_path_with_cx_matches_cpu",
    ),
    _evidence(
        "FQKI-TRITON-SV-005-A",
        "tests/unit/test_single_qubit_loop_triton.py::test_repeated_rx_rz_cuda_matches_reference",
        gradient_tests=(
            "tests/unit/test_single_qubit_loop_triton.py::test_repeated_rx_rz_cuda_matches_reference",
        ),
        capability_tests=(
            "tests/unit/test_single_qubit_loop_triton.py::test_repeated_rx_rz_cpu_fallback_matches_reference",
        ),
    ),
    _evidence(
        "FQKI-TRITON-SV-006-A",
        "tests/unit/test_statevector_triton.py::test_fused_transpose_1q_matches_unpack_then_gate",
    ),
    _evidence(
        "FQKI-TRITON-SV-007-A",
        "tests/test_statevector_triton_gates.py::test_control_one_pack_unpack_matches_index_reference",
    ),
    _evidence(
        "FQKI-TRITON-SV-008-A",
        "tests/test_statevector_triton_gates.py::test_control_one_pack_unpack_matches_index_reference",
    ),
    _evidence(
        "FQKI-TRITON-GR-001-A",
        "tests/unit/test_statevector_triton.py::test_fused_vjp_and_adjoint_match_pytorch",
        gradient_tests=(
            "tests/unit/test_statevector_triton.py::test_fused_vjp_and_adjoint_match_pytorch",
        ),
    ),
    _evidence(
        "FQKI-TRITON-GR-002-A",
        "tests/unit/test_statevector_triton.py::test_fused_reversible_vjp_matches_pytorch",
        gradient_tests=(
            "tests/unit/test_statevector_triton.py::test_fused_reversible_vjp_matches_pytorch",
        ),
    ),
    _evidence(
        "FQKI-TRITON-GR-003-A",
        "tests/unit/test_statevector_triton.py::test_fused_sharded_vjp_and_adjoint_matches_global_pair",
        gradient_tests=(
            "tests/unit/test_statevector_triton.py::test_fused_sharded_vjp_and_adjoint_matches_global_pair",
        ),
    ),
    _evidence(
        "FQKI-TRITON-GR-004-A",
        "tests/unit/test_single_qubit_loop_triton.py::test_repeated_rx_rz_cuda_tangents_match_cpu_reference",
        gradient_tests=(
            "tests/unit/test_single_qubit_loop_triton.py::test_repeated_rx_rz_cuda_tangents_match_cpu_reference",
        ),
        capability_tests=(
            "tests/unit/test_single_qubit_loop_triton.py::test_repeated_rx_rz_cpu_tangents_match_jacobian",
        ),
    ),
    _evidence(
        "FQKI-TRITON-GR-005-A",
        "tests/unit/test_two_qubit_pauli_tangent_triton.py::test_two_qubit_pauli_tangent_cuda_matches_reference",
        gradient_tests=(
            "tests/unit/test_two_qubit_pauli_tangent_triton.py::test_two_qubit_pauli_tangent_cuda_matches_reference",
        ),
        capability_tests=(
            "tests/unit/test_two_qubit_pauli_tangent_triton.py::test_two_qubit_pauli_tangent_cpu_fallback_matches_reference",
        ),
    ),
    _evidence(
        "FQKI-TRITON-GR-006-A",
        "tests/unit/test_hva_forward_tangent_triton.py::test_hva_forward_tangents_match_statevector_jacobian",
        gradient_tests=(
            "tests/unit/test_hva_forward_tangent_triton.py::test_hva_forward_tangents_match_statevector_jacobian",
        ),
    ),
    _evidence(
        "FQKI-TRITON-MPS-001-A",
        "tests/unit/test_mps_two_site_triton.py::test_fused_mps_two_site_forward_and_backward",
        gradient_tests=(
            "tests/unit/test_mps_two_site_triton.py::test_fused_mps_two_site_forward_and_backward",
        ),
        capability_tests=(
            "tests/unit/test_mps_two_site_triton.py::test_fused_mps_two_site_cpu_fallback_matches_reference",
        ),
        benchmark_artifacts=(
            "benchmarks/results/local/mps_two_site_dispatch_a800.json",
        ),
    ),
    _evidence(
        "FQKI-TRITON-MPS-002-A",
        "tests/unit/test_mps_two_site_triton.py::test_fused_mps_range_projection_avoids_full_matrix_with_correct_values",
        "tests/unit/test_mps_low_rank.py::test_fixed_rank_two_site_opt_in_routes_inference_but_preserves_training_fallback",
        capability_tests=(
            "tests/unit/test_mps_two_site_triton.py::test_fused_mps_range_projection_cpu_fallback_matches_reference",
            "tests/unit/test_mps_low_rank.py::test_fixed_rank_two_site_opt_in_routes_inference_but_preserves_training_fallback",
        ),
        benchmark_artifacts=(
            "benchmarks/results/local/mps_projected_two_site_dispatch_a800.json",
        ),
    ),
    _evidence(
        "FQKI-TRITON-MPS-003-A",
        "tests/unit/test_mps_one_site_triton.py::test_fused_mps_one_site_forward_and_backward",
        "tests/unit/test_mps_one_site_catalog_dispatch.py::test_mps_one_site_bucket_uses_catalog_by_default_and_preserves_gradients",
        gradient_tests=(
            "tests/unit/test_mps_one_site_triton.py::test_fused_mps_one_site_forward_and_backward",
            "tests/unit/test_mps_one_site_catalog_dispatch.py::test_mps_one_site_bucket_uses_catalog_by_default_and_preserves_gradients",
        ),
        capability_tests=(
            "tests/unit/test_mps_one_site_triton.py::test_fused_mps_one_site_cpu_fallback_matches_reference",
            "tests/unit/test_mps_one_site_catalog_dispatch.py::test_mps_one_site_rollout_defaults_on_and_supports_kill_switch",
            "tests/unit/test_mps_one_site_catalog_dispatch.py::test_mps_one_site_kill_switch_uses_reference",
        ),
        benchmark_artifacts=(
            "benchmarks/results/local/mps_one_site_dispatch_a800.json",
        ),
    ),
    _evidence(
        "FQKI-TRITON-MPS-004-A",
        "tests/unit/test_mps_environment_triton.py::test_fused_mps_environment_cuda_matches_reference",
        "tests/unit/test_mps_environment_catalog_dispatch.py::test_mps_environment_product_path_uses_catalog",
        capability_tests=(
            "tests/unit/test_mps_environment_triton.py::test_fused_mps_environment_cpu_fallback_matches_reference_and_gradients",
            "tests/unit/test_mps_environment_triton.py::test_fused_mps_environment_large_shape_uses_fallback",
            "tests/unit/test_mps_environment_catalog_dispatch.py::test_mps_environment_rollout_defaults_on_and_supports_kill_switch",
            "tests/unit/test_mps_environment_catalog_dispatch.py::test_mps_environment_route_enforces_evidenced_window",
            "tests/unit/test_mps_environment_catalog_dispatch.py::test_mps_environment_route_rejects_gradients",
            "tests/unit/test_mps_environment_catalog_dispatch.py::test_mps_environment_kill_switch_uses_reference",
        ),
        benchmark_artifacts=(
            "benchmarks/results/local/mps_environment_dispatch_a800.json",
        ),
    ),
    _evidence(
        "FQKI-TRITON-MPS-005-A",
        "tests/unit/test_mps_environment_channels_triton.py::test_fused_mps_environment_channels_cuda_matches_reference",
        "tests/unit/test_mps_environment_channels_catalog_dispatch.py::test_mps_environment_channels_product_path_uses_catalog",
        capability_tests=(
            "tests/unit/test_mps_environment_channels_triton.py::test_fused_mps_environment_channels_cpu_fallback_preserves_gradients",
            "tests/unit/test_mps_environment_channels_triton.py::test_fused_mps_environment_channels_outside_window_uses_fallback",
            "tests/unit/test_mps_environment_channels_catalog_dispatch.py::test_mps_environment_channels_rollout_defaults_on_and_supports_kill_switch",
            "tests/unit/test_mps_environment_channels_catalog_dispatch.py::test_mps_environment_channels_route_enforces_evidenced_window",
            "tests/unit/test_mps_environment_channels_catalog_dispatch.py::test_mps_environment_channels_route_rejects_gradients",
            "tests/unit/test_mps_environment_channels_catalog_dispatch.py::test_mps_environment_channels_kill_switch_uses_reference",
        ),
        benchmark_artifacts=(
            "benchmarks/results/local/mps_environment_channels_dispatch_a800.json",
        ),
    ),
    _evidence(
        "FQKI-TRITON-MPS-006-A",
        "tests/unit/test_mps_observable_adjoint_triton.py::test_fused_mps_hermitian_observable_adjoint_cuda_matches_autograd",
        "tests/unit/test_mps_observable_adjoint_catalog_dispatch.py::test_mps_observable_adjoint_runtime_uses_catalog",
        gradient_tests=(
            "tests/unit/test_mps_observable_adjoint_triton.py::test_fused_mps_hermitian_observable_adjoint_cuda_matches_autograd",
        ),
        capability_tests=(
            "tests/unit/test_mps_observable_adjoint_triton.py::test_fused_mps_hermitian_observable_adjoint_cpu_fallback_matches_autograd",
            "tests/unit/test_mps_observable_adjoint_triton.py::test_fused_mps_hermitian_observable_adjoint_outside_window_uses_fallback",
            "tests/unit/test_mps_observable_adjoint_triton.py::test_fused_mps_hermitian_observable_adjoint_noncontiguous_uses_fallback",
            "tests/unit/test_mps_observable_adjoint_catalog_dispatch.py::test_mps_observable_adjoint_rollout_defaults_on_and_supports_kill_switch",
            "tests/unit/test_mps_observable_adjoint_catalog_dispatch.py::test_mps_observable_adjoint_route_enforces_evidenced_window",
            "tests/unit/test_mps_observable_adjoint_catalog_dispatch.py::test_mps_observable_adjoint_route_requires_hermitian_contract",
            "tests/unit/test_mps_observable_adjoint_catalog_dispatch.py::test_mps_observable_adjoint_reference_path_reports_fallback",
            "tests/unit/test_mps_observable_adjoint_catalog_dispatch.py::test_mps_observable_adjoint_kill_switch_uses_reference",
        ),
        benchmark_artifacts=(
            "benchmarks/results/local/mps_observable_adjoint_dispatch_a800.json",
        ),
    ),
    _evidence(
        "FQKI-TRITON-MPS-007-A",
        "tests/unit/test_mps_wire_probabilities_triton.py::test_fused_mps_wire_probabilities_cuda_matches_reference",
        "tests/unit/test_mps_wire_probability_catalog_dispatch.py::test_mps_wire_probability_runtime_uses_catalog",
        capability_tests=(
            "tests/unit/test_mps_wire_probabilities_triton.py::test_fused_mps_wire_probabilities_cpu_fallback_matches_reference",
            "tests/unit/test_mps_wire_probabilities_triton.py::test_fused_mps_wire_probabilities_unsupported_input_uses_fallback",
            "tests/unit/test_mps_wire_probabilities_triton.py::test_fused_mps_wire_probabilities_validates_input",
            "tests/unit/test_mps_wire_probability_catalog_dispatch.py::test_mps_wire_probability_rollout_defaults_on_and_supports_kill_switch",
            "tests/unit/test_mps_wire_probability_catalog_dispatch.py::test_mps_wire_probability_reference_path_reports_fallback",
            "tests/unit/test_mps_wire_probability_catalog_dispatch.py::test_mps_wire_probability_route_enforces_evidenced_window",
            "tests/unit/test_mps_wire_probability_catalog_dispatch.py::test_mps_wire_probability_kill_switch_uses_reference",
        ),
        benchmark_artifacts=(
            "benchmarks/results/local/mps_wire_probability_dispatch_a800.json",
        ),
    ),
    _evidence(
        "FQKI-TRITON-NUM-001-A",
        "tests/unit/test_triton_complex_bmm.py::test_fused_complex_bmm_forward_and_backward_match_torch",
        gradient_tests=(
            "tests/unit/test_triton_complex_bmm.py::test_fused_complex_bmm_forward_and_backward_match_torch",
        ),
        capability_tests=(
            "tests/unit/test_triton_complex_bmm.py::test_fused_complex_bmm_cpu_fallback_matches_torch",
        ),
    ),
    _evidence(
        "FQKI-TRITON-NUM-002-A",
        "tests/unit/test_real_imag_kernels.py::test_fused_layout_route_does_not_materialize_canonical_inputs",
        gradient_tests=(
            "tests/unit/test_real_imag_kernels.py::test_fused_layout_route_does_not_materialize_canonical_inputs",
        ),
        capability_tests=(
            "tests/unit/test_triton_complex_bmm.py::test_fused_complex_layout_bmm_cpu_fallback_matches_torch",
        ),
        benchmark_artifacts=(
            "benchmarks/results/local/tn_layout_contraction_a800.json",
        ),
    ),
    _evidence(
        "FQKI-FLAGTREE-SV-001-A",
        "tests/gpu/test_flagtree_tle_statevector.py::test_flagtree_tle_local_1q_matches_pytorch",
        capability_tests=(
            "tests/unit/test_flagtree_tle_provider.py::test_tle_capability_maps_cuda_target_to_nvidia_registry",
        ),
        benchmark_artifacts=(
            "benchmarks/results/local/flagtree_tle_local_1q_a800.json",
        ),
    ),
)


__all__ = ["EVIDENCE"]
