"""Executable implementations registered against kernel semantics."""

from __future__ import annotations

from .schema import KernelDirection, KernelImplementation, KernelMaturity


def _triton(
    implementation_id: str,
    semantic_id: str,
    module: str,
    symbol: str,
    *,
    layouts: tuple[str, ...],
    directions: tuple[KernelDirection, ...] = ("forward",),
    addressing: tuple[str, ...] = ("local",),
    maturity: KernelMaturity = "experimental",
    internal_fallback: bool = False,
) -> KernelImplementation:
    return KernelImplementation(
        implementation_id=implementation_id,
        semantic_id=semantic_id,
        provider="triton",
        module=f"flagquantum.kernels.triton.{module}",
        symbol=symbol,
        devices=("cuda",),
        dtypes=("complex64",),
        layouts=layouts,
        directions=directions,
        addressing=addressing,
        maturity=maturity,
        internal_fallback=internal_fallback,
    )


def _flagtree(
    implementation_id: str,
    semantic_id: str,
    module: str,
    symbol: str,
    *,
    layouts: tuple[str, ...],
    directions: tuple[KernelDirection, ...] = ("forward",),
    addressing: tuple[str, ...] = ("local",),
    maturity: KernelMaturity = "experimental",
) -> KernelImplementation:
    return KernelImplementation(
        implementation_id=implementation_id,
        semantic_id=semantic_id,
        provider="flagtree",
        module=module,
        symbol=symbol,
        devices=("cuda",),
        dtypes=("complex64",),
        layouts=layouts,
        directions=directions,
        addressing=addressing,
        maturity=maturity,
    )


IMPLEMENTATIONS: tuple[KernelImplementation, ...] = (
    _triton(
        "FQKI-TRITON-SV-001-A",
        "statevector.apply.matrix_1q.local",
        "statevector_gates",
        "apply_complex64_local_1q",
        layouts=("flat_statevector",),
        directions=("forward",),
        maturity="provisional",
    ),
    _triton(
        "FQKI-TRITON-SV-001-B",
        "statevector.apply.matrix_1q.local",
        "statevector_gates",
        "single_qubit_matrix",
        layouts=("flat_statevector",),
        directions=("forward", "backward"),
    ),
    _triton(
        "FQKI-TRITON-SV-002-A",
        "statevector.apply.cnot.local",
        "statevector_gates",
        "apply_complex64_local_cx_inplace",
        layouts=("flat_statevector",),
        maturity="provisional",
    ),
    _triton(
        "FQKI-TRITON-SV-003-A",
        "statevector.apply.cnot_sequence.local",
        "statevector_gates",
        "apply_complex64_local_cx_segment",
        layouts=("flat_statevector",),
        maturity="provisional",
    ),
    _triton(
        "FQKI-TRITON-SV-003-B",
        "statevector.apply.cnot_sequence.local",
        "statevector_gates",
        "cx_sequence",
        layouts=("flat_statevector",),
        directions=("forward", "backward"),
    ),
    _triton(
        "FQKI-TRITON-SV-004-A",
        "statevector.apply.ry_rz_pair.local",
        "statevector_gates",
        "ry_rz_pair",
        layouts=("flat_statevector",),
        directions=("forward",),
        maturity="provisional",
    ),
    _triton(
        "FQKI-TRITON-SV-005-A",
        "statevector.apply.rx_rz_sequence.local",
        "single_qubit_loop",
        "repeated_rx_rz",
        layouts=("flat_statevector",),
        directions=("forward", "backward"),
        internal_fallback=True,
        maturity="provisional",
    ),
    _triton(
        "FQKI-TRITON-SV-006-A",
        "statevector.distributed.transpose_apply_1q",
        "statevector_gates",
        "apply_complex64_transpose_1q_inplace",
        layouts=("sharded_statevector",),
        addressing=("distributed", "transpose"),
        maturity="provisional",
    ),
    _triton(
        "FQKI-TRITON-SV-007-A",
        "statevector.transport.control_subspace_pack",
        "statevector_gates",
        "pack_complex64_control_one",
        layouts=("flat_statevector", "packed_subspace"),
        addressing=("distributed", "control_subspace"),
        maturity="provisional",
    ),
    _triton(
        "FQKI-TRITON-SV-008-A",
        "statevector.transport.control_subspace_unpack",
        "statevector_gates",
        "unpack_complex64_control_one",
        layouts=("packed_subspace", "flat_statevector"),
        addressing=("distributed", "control_subspace"),
        maturity="provisional",
    ),
    _triton(
        "FQKI-TRITON-GR-001-A",
        "gradient.vjp.adjoint_1q.local",
        "statevector_adjoint",
        "fused_complex64_local_1q_vjp_adjoint",
        layouts=("flat_statevector",),
        directions=("vjp",),
        maturity="provisional",
    ),
    _triton(
        "FQKI-TRITON-GR-002-A",
        "gradient.vjp.reversible_1q.local",
        "statevector_adjoint",
        "fused_complex64_local_1q_reversible_vjp",
        layouts=("flat_statevector",),
        directions=("vjp",),
        maturity="provisional",
    ),
    _triton(
        "FQKI-TRITON-GR-003-A",
        "gradient.vjp.adjoint_1q.sharded",
        "statevector_adjoint",
        "fused_complex64_sharded_1q_vjp_adjoint",
        layouts=("sharded_statevector",),
        directions=("vjp",),
        addressing=("distributed",),
        maturity="provisional",
    ),
    _triton(
        "FQKI-TRITON-GR-004-A",
        "gradient.jacobian.rx_rz_sequence",
        "single_qubit_loop",
        "repeated_rx_rz_tangents",
        layouts=("flat_statevector", "parameter_major_tangents"),
        directions=("jacobian",),
        internal_fallback=True,
        maturity="provisional",
    ),
    _triton(
        "FQKI-TRITON-GR-005-A",
        "gradient.jacobian.pauli_rotation_sequence_2q",
        "two_qubit_pauli_tangent",
        "repeated_rxx_ryy_rzz_tangents",
        layouts=("flat_statevector", "parameter_major_tangents"),
        directions=("jacobian",),
        internal_fallback=True,
        maturity="provisional",
    ),
    _triton(
        "FQKI-TRITON-GR-006-A",
        "gradient.forward_tangent.heisenberg_hva",
        "hva_forward_tangent",
        "heisenberg_hva_forward_tangents",
        layouts=("flat_statevector", "parameter_major_tangents"),
        directions=("jacobian",),
        maturity="provisional",
    ),
    _triton(
        "FQKI-TRITON-MPS-001-A",
        "mps.contract.two_site_gate",
        "mps_two_site",
        "fused_mps_two_site",
        layouts=("mps_two_site",),
        directions=("forward", "backward"),
        internal_fallback=True,
    ),
    _triton(
        "FQKI-TRITON-MPS-002-A",
        "mps.contract.two_site_gate_projected",
        "mps_two_site",
        "fused_mps_range_projection",
        layouts=("mps_two_site", "projected_range"),
        internal_fallback=True,
    ),
    _triton(
        "FQKI-TRITON-MPS-003-A",
        "mps.contract.one_site_gate",
        "mps_one_site",
        "fused_mps_one_site",
        layouts=("mps_one_site",),
        directions=("forward", "backward"),
        maturity="provisional",
        internal_fallback=True,
    ),
    _triton(
        "FQKI-TRITON-MPS-004-A",
        "mps.environment.transfer_identity_z",
        "mps_environment",
        "fused_mps_environment_transfer",
        layouts=("mps_environment",),
        maturity="provisional",
        internal_fallback=True,
    ),
    _triton(
        "FQKI-TRITON-MPS-005-A",
        "mps.environment.transfer_channels",
        "mps_environment",
        "fused_mps_environment_channels",
        layouts=("mps_environment_channels",),
        maturity="provisional",
        internal_fallback=True,
    ),
    _triton(
        "FQKI-TRITON-MPS-006-A",
        "mps.gradient.hermitian_observable_adjoint.local",
        "mps_observable_adjoint",
        "fused_mps_hermitian_observable_adjoint",
        layouts=("mps_local_observable",),
        directions=("vjp",),
        maturity="provisional",
        internal_fallback=True,
    ),
    _triton(
        "FQKI-TRITON-MPS-007-A",
        "mps.measurement.wire_probabilities.local",
        "mps_wire_probabilities",
        "fused_mps_wire_probabilities",
        layouts=("mps_site_tensor",),
        maturity="provisional",
        internal_fallback=True,
    ),
    _triton(
        "FQKI-TRITON-MEAS-001-A",
        "measurement.probabilities.statevector",
        "statevector_measurement",
        "statevector_probabilities",
        layouts=("flat_statevector",),
        directions=("forward", "backward"),
        maturity="provisional",
        internal_fallback=True,
    ),
    _triton(
        "FQKI-TRITON-MEAS-002-A",
        "measurement.expectation.pauli_product.statevector",
        "statevector_measurement",
        "statevector_pauli_expectation",
        layouts=("flat_statevector",),
        directions=("forward", "backward"),
        maturity="provisional",
        internal_fallback=True,
    ),
    _triton(
        "FQKI-TRITON-MEAS-003-A",
        "measurement.probabilities.marginal.statevector",
        "statevector_measurement",
        "statevector_marginal_probabilities",
        layouts=("flat_statevector", "selected_wire_order"),
        directions=("forward", "backward"),
        maturity="provisional",
        internal_fallback=True,
    ),
    _triton(
        "FQKI-TRITON-NUM-001-A",
        "numerics.matmul.complex_batched",
        "complex_bmm",
        "fused_complex_bmm",
        layouts=("batched_matrix",),
        directions=("forward", "backward"),
        internal_fallback=True,
    ),
    _triton(
        "FQKI-TRITON-NUM-002-A",
        "numerics.matmul.complex_batched_layout",
        "complex_bmm",
        "fused_complex_layout_bmm",
        layouts=("explicit_strided_batch",),
        directions=("forward", "backward"),
        internal_fallback=True,
    ),
    _flagtree(
        "FQKI-FLAGTREE-SV-001-A",
        "statevector.apply.matrix_1q.local",
        "flagquantum.kernels.flagtree",
        "apply_complex64_local_1q_tle",
        layouts=("flat_statevector",),
    ),
    _flagtree(
        "FQKI-FLAGTREE-SV-006-A",
        "statevector.distributed.transpose_apply_1q",
        "flagquantum.kernels.flagtree",
        "apply_complex64_transpose_1q_tle_inplace",
        layouts=("sharded_statevector",),
        addressing=("distributed", "transpose"),
    ),
    _flagtree(
        "FQKI-FLAGTREE-SV-007-A",
        "statevector.transport.control_subspace_pack",
        "flagquantum.kernels.flagtree",
        "pack_complex64_control_one_tle",
        layouts=("flat_statevector", "packed_subspace"),
        addressing=("distributed", "control_subspace"),
    ),
    _flagtree(
        "FQKI-FLAGTREE-SV-008-A",
        "statevector.transport.control_subspace_unpack",
        "flagquantum.kernels.flagtree",
        "unpack_complex64_control_one_tle",
        layouts=("packed_subspace", "flat_statevector"),
        addressing=("distributed", "control_subspace"),
    ),
    _flagtree(
        "FQKI-FLAGTREE-GR-003-A",
        "gradient.vjp.adjoint_1q.sharded",
        "flagquantum.kernels.flagtree",
        "fused_complex64_sharded_1q_vjp_adjoint_tle",
        layouts=("sharded_statevector",),
        directions=("vjp",),
        addressing=("distributed",),
    ),
)


__all__ = ["IMPLEMENTATIONS"]
