"""
OpenQASM Exporter for FlagQuantum
Supports exporting to QASM 2.0 and 3.0 formats
"""

from typing import List, Optional, Union

import torch


class QASMExporter:
    """
    Export FlagQuantum's op_history to OpenQASM 2.0 or 3.0 format.

    Example:
        >>> exporter = QASMExporter()
        >>> # Export to QASM 3.0
        >>> exporter.export(qdev, "circuit.qasm", version=3.0)
        >>> # Export to QASM 2.0 (Qiskit compatible)
        >>> exporter.export(qdev, "circuit_qiskit.qasm", version=2.0)
    """

    def __init__(self):
        # Common gate mapping
        self.gate_map = {
            # Single-qubit gates
            "i": "id",
            "x": "x",
            "y": "y",
            "z": "z",
            "h": "h",
            "s": "s",
            "sdg": "sdg",
            "t": "t",
            "tdg": "tdg",
            "sx": "sx",
            "sxdg": "sxdg",
            # Two-qubit gates
            "cx": "cx",
            "cnot": "cx",
            "cy": "cy",
            "cz": "cz",
            "swap": "swap",
            "cphase": "cp",
            "ccx": "ccx",
            "cswap": "cswap",
            # Rotation gates
            "rx": "rx",
            "ry": "ry",
            "rz": "rz",
            "u1": "u1",
            "u2": "u2",
            "u3": "u3",
            # Phase gates
            "p": "p",
            "phase": "p",
            # Measurement
            "measure_allZ": "measure",
        }

        # Gates requiring special handling
        self.custom_gates = {"crx", "cry", "crz", "cp", "rxx", "ryy", "rzz"}

    # ==================== Common Methods ====================

    def _format_params(self, params, version: float = 3.0) -> str:
        """Format parameters for QASM output."""
        if params is None:
            return ""

        # Extract parameter values
        if isinstance(params, (int, float)):
            values = [params]
        elif isinstance(params, list):
            values = params
        elif isinstance(params, torch.Tensor):
            values = params.detach().cpu().numpy().flatten().tolist()
        else:
            return ""

        # Parameter format is the same for QASM 2.0 and 3.0
        if len(values) == 1:
            return f"({values[0]})"
        return f"({', '.join(str(v) for v in values)})"

    def _get_param_value(self, params) -> Optional[float]:
        """Extract a single parameter value (used for QASM 2.0)."""
        if params is None:
            return None
        if isinstance(params, (int, float)):
            return params
        if isinstance(params, list) and len(params) > 0:
            return params[0]
        if isinstance(params, torch.Tensor) and params.numel() > 0:
            return params.flatten()[0].item()
        return None

    # ==================== QASM 3.0 Format ====================

    def _format_wires_qasm3(self, wires: Union[int, List[int]]) -> str:
        """Format wires for QASM 3.0 output."""
        if isinstance(wires, int):
            return f"q[{wires}]"
        return ", ".join(f"q[{w}]" for w in wires)

    def _format_gate_call_qasm3(self, gate_name: str, wires, params=None) -> str:
        """Format a gate call for QASM 3.0."""
        qasm_name = self.gate_map.get(gate_name, gate_name)
        params_str = self._format_params(params, version=3.0) if params else ""
        wires_str = self._format_wires_qasm3(wires)

        if params_str:
            return f"  {qasm_name}{params_str} {wires_str};"
        return f"  {qasm_name} {wires_str};"

    def _handle_measure_qasm3(self, qdev, has_measure: bool) -> List[str]:
        """Handle measurement for QASM 3.0."""
        lines = []
        if has_measure:
            # Measurement already present, use array syntax
            lines.append(f"  bit[{qdev.n_wires}] c;")
            lines.append("  c = measure q;")
        else:
            # No measurement, add final measurements
            lines.append("")
            lines.append("// Final measurements")
            for i in range(qdev.n_wires):
                lines.append(f"  bit b{i};")
                lines.append(f"  b{i} = measure q[{i}];")
        return lines

    def export_qasm3(self, qdev, filename: Optional[str] = None) -> Optional[str]:
        """Export to OpenQASM 3.0 format."""
        lines = [
            "OPENQASM 3.0;",
            'include "stdgates.inc";',
            "// Generated by FlagQuantum",
            f"// Number of qubits: {qdev.n_wires}",
            f"// Total operations: {len(qdev.op_history)}",
            "",
            f"qubit[{qdev.n_wires}] q;",
            "",
            "// Initialize to |0...0⟩",
            "",
        ]

        has_measure = False

        for op in qdev.op_history:
            gate_name = op.get("name_or_mat", "unknown")
            wires = op.get("wires", [])
            params = op.get("params", None)

            if isinstance(wires, int):
                wires = [wires]

            if gate_name == "unknown":
                continue

            if gate_name == "measure_allZ":
                has_measure = True
                continue

            if gate_name == "cnot":
                gate_name = "cx"

            if gate_name in self.gate_map:
                lines.append(self._format_gate_call_qasm3(gate_name, wires, params))
            else:
                lines.append(f"  // Unsupported gate: {gate_name}")

        # Add measurement
        lines.extend(self._handle_measure_qasm3(qdev, has_measure))

        qasm_str = "\n".join(lines)

        if filename:
            with open(filename, "w") as f:
                f.write(qasm_str)
            print(f"✅ QASM 3.0 exported to {filename}")

        return qasm_str

    # ==================== QASM 2.0 Format ====================

    def _format_gate_call_qasm2(self, gate_name: str, wires, params=None) -> str:
        """Format a gate call for QASM 2.0."""
        qasm_name = self.gate_map.get(gate_name, gate_name)

        if gate_name in ["rx", "ry", "rz", "u1", "u2", "u3", "p"]:
            param_val = self._get_param_value(params)
            param_str = f"({param_val})" if param_val is not None else ""
            return f"{qasm_name}{param_str} q[{wires[0]}];"

        if gate_name in ["cx", "cy", "cz", "swap", "cnot"]:
            gate = "cx" if gate_name == "cnot" else gate_name
            return f"{gate} q[{wires[0]}], q[{wires[1]}];"

        if gate_name in ["crx", "cry", "crz"]:
            param_val = self._get_param_value(params)
            param_str = f"({param_val})" if param_val is not None else ""
            return f"{gate_name}{param_str} q[{wires[0]}], q[{wires[1]}];"

        # Single-qubit gate
        return f"{qasm_name} q[{wires[0]}];"

    def _handle_measure_qasm2(self, qdev, has_measure: bool) -> List[str]:
        """Handle measurement for QASM 2.0."""
        lines = []
        for wire in range(qdev.n_wires):
            lines.append(f"measure q[{wire}] -> c[{wire}];")
        return lines

    def export_qasm2(self, qdev, filename: Optional[str] = None) -> Optional[str]:
        """Export to QASM 2.0 format (Qiskit compatible)."""
        lines = [
            "OPENQASM 2.0;",
            'include "qelib1.inc";',
            "// Generated by FlagQuantum",
            f"qreg q[{qdev.n_wires}];",
            f"creg c[{qdev.n_wires}];",
            "",
        ]

        for op in qdev.op_history:
            gate_name = op.get("name_or_mat", "unknown")
            wires = op.get("wires", [])
            params = op.get("params", None)

            if isinstance(wires, int):
                wires = [wires]

            if gate_name == "unknown":
                continue

            if gate_name == "measure_allZ":
                continue

            if gate_name in self.gate_map:
                lines.append(self._format_gate_call_qasm2(gate_name, wires, params))

        # Add measurement
        lines.extend(self._handle_measure_qasm2(qdev, has_measure=True))

        qasm_str = "\n".join(lines)

        if filename:
            with open(filename, "w") as f:
                f.write(qasm_str)
            print(f"✅ QASM 2.0 exported to {filename}")

        return qasm_str

    # ==================== Unified Export Interface ====================

    def export(
        self, qdev, filename: Optional[str] = None, version: float = 3.0
    ) -> Optional[str]:
        """
        Unified export interface.

        Args:
            qdev: DistributedQuantumDevice instance
            filename: Output filename. If None, returns string instead
            version: QASM version, either 2.0 or 3.0

        Returns:
            QASM string if filename is None, otherwise None
        """
        if version == 2.0:
            return self.export_qasm2(qdev, filename)
        elif version == 3.0:
            return self.export_qasm3(qdev, filename)
        else:
            raise ValueError(f"Unsupported QASM version: {version}. Use 2.0 or 3.0")


# Convenience functions
def export_to_qasm(qdev, filename: str, version: float = 3.0) -> None:
    """Export circuit to a QASM file."""
    exporter = QASMExporter()
    exporter.export(qdev, filename, version)


def export_to_qasm_str(qdev, version: float = 3.0) -> str:
    """Export circuit to a QASM string."""
    exporter = QASMExporter()
    return exporter.export(qdev, version=version)


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "QASMExporter",
    "export_to_qasm",
    "export_to_qasm_str",
]

# Example usage
if __name__ == "__main__":
    import torch

    import flagquantum as fq

    # Create quantum device
    qdev = fq.DistributedQuantumDevice(n_wires=3, bsz=1, device="cpu", record_op=True)

    # Build circuit
    fq.H(wires=[0])(qdev)
    fq.RX(wires=[1], init_params=torch.tensor([0.5]))(qdev)
    fq.CNOT(wires=[0, 1])(qdev)
    fq.RZ(wires=[2], init_params=torch.tensor([0.3]))(qdev)
    fq.measure_allZ(qdev)

    # Export to QASM 3.0
    fq.export_to_qasm(qdev, "circuit_qasm3.qasm", version=3.0)

    # Export to QASM 2.0 (Qiskit compatible)
    fq.export_to_qasm(qdev, "circuit_qasm2.qasm", version=2.0)

    # Get QASM string
    qasm_str = export_to_qasm_str(qdev, version=3.0)
    print(qasm_str)

    # Example: Import QASM 3.0 into qiskit
    # import qiskit.qasm3
    # circuit = qiskit.qasm3.load("circuit_qasm3.qasm")
    # circuit.draw()

    # Example: Import QASM 2.0 into qiskit
    # from qiskit import QuantumCircuit
    # circuit = QuantumCircuit.from_qasm_file("circuit_qasm2.qasm")
    # circuit.draw()
