"""Compute targets reached through an external task control plane.

Remote adapters submit work and translate external task identifiers, status,
and results. Directly controlled CPU, GPU, and accelerator resources belong in
``flagquantum.compute``.
"""

from .qpu import (
    DEPLOYMENT_SUBMISSION_RECEIPT_SCHEMA,
    IONQ_GATE_SETS,
    AmazonBraketProvider,
    AzureQuantumProvider,
    AzureSubmissionPreview,
    BraketSubmissionPreview,
    DeploymentResult,
    HttpQuantumProvider,
    IonQProvider,
    IQMProvider,
    NeutralAtomProvider,
    ProviderCredentials,
    ProviderEndpoints,
    ProviderSubmissionPreview,
    ProviderTaskHandle,
    QuafuProvider,
    QuantinuumProvider,
    QuantumCloudTransport,
    QuantumProvider,
    UrllibTransport,
    azure_backend_profile,
    braket_backend_profile,
    build_result_metadata,
    build_submission_receipt,
    interaction_edges,
    ionq_backend_profile,
    iqm_backend_profile,
    neutral_atom_backend_profile,
    preflight_submission,
    quafu_noise_model_from_chip_info,
    quantinuum_backend_profile,
    validate_deployment_result,
)

__all__ = (
    "AmazonBraketProvider",
    "AzureQuantumProvider",
    "AzureSubmissionPreview",
    "BraketSubmissionPreview",
    "DEPLOYMENT_SUBMISSION_RECEIPT_SCHEMA",
    "DeploymentResult",
    "HttpQuantumProvider",
    "IONQ_GATE_SETS",
    "IQMProvider",
    "IonQProvider",
    "NeutralAtomProvider",
    "ProviderCredentials",
    "ProviderEndpoints",
    "ProviderSubmissionPreview",
    "ProviderTaskHandle",
    "QuafuProvider",
    "QuantinuumProvider",
    "QuantumCloudTransport",
    "QuantumProvider",
    "UrllibTransport",
    "azure_backend_profile",
    "braket_backend_profile",
    "build_result_metadata",
    "build_submission_receipt",
    "interaction_edges",
    "ionq_backend_profile",
    "iqm_backend_profile",
    "neutral_atom_backend_profile",
    "preflight_submission",
    "quafu_noise_model_from_chip_info",
    "quantinuum_backend_profile",
    "validate_deployment_result",
)
