"""Generate and validate the CUDA-Q parity scoreboard.

The parity matrix contract ``contracts/cudaq-parity-matrix.toml`` is the source
of truth. This tool validates it against the repository and renders
``docs/reference/CUDAQ_PARITY_MATRIX.md`` from it, so the published scoreboard
cannot drift from the contract.

Validation is fail-closed. An unknown status, priority, or dependency class; a
``maturity_ref`` that is absent from ``capability-maturity.toml``; a `supported`
row with no registry entry; a missing or malformed evidence item; a stale
generated document; a surface-ownership entry that does not match the inventory
it explains; and a component version mapping the recorded release lines do not
support all exit non-zero.

Evidence is declared per row and falls back to the domain default. An item is
either a repository-relative path, which must exist, or a ``search:`` token
recording the negative search that established an absence.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python 3.10 compatibility
    import tomli as tomllib

REPO_ROOT = Path(__file__).resolve().parent.parent
CONTRACT_PATH = REPO_ROOT / "contracts" / "cudaq-parity-matrix.toml"
MATURITY_PATH = REPO_ROOT / "capability-maturity.toml"
EXPORT_CONTRACT_PATH = REPO_ROOT / "contracts" / "cudaq-export-contract.toml"
GAP_MATRIX_PATH = REPO_ROOT / "contracts" / "interop-capability-gap-matrix.toml"
OUTPUT_PATH = REPO_ROOT / "docs" / "reference" / "CUDAQ_PARITY_MATRIX.md"

EXPECTED_SCHEMA = "flagquantum_cudaq_parity_matrix_v1"
GENERATED_BANNER = "<!-- Generated by tools/parity_matrix.py. Do not edit by hand. -->"
EVIDENCE_SEARCH_PREFIX = "search:"

STATUS_ORDER = ("supported", "partial", "unsupported", "out_of_scope")
PRIORITY_ORDER = ("now", "next", "later", "excluded")
DEPENDENCY_ORDER = (
    "A_nvidia_proprietary",
    "B_open_neutral",
    "C_flagos_replacement",
    "none",
)
PROBE_STATUS_ORDER = ("runnable", "measured")


class ContractError(Exception):
    """A parity contract violates a rule the repository depends on."""


def load_toml(path: Path) -> dict[str, Any]:
    """Load a TOML document by text, so the parser is not the thing under test."""
    return tomllib.loads(path.read_text(encoding="utf-8"))


def load_inputs() -> tuple[dict[str, Any], dict[str, Any]]:
    """Return the parity contract and the capability registry it validates against."""
    for path in (CONTRACT_PATH, MATURITY_PATH):
        if not path.is_file():
            raise ContractError(f"missing file: {path.relative_to(REPO_ROOT)}")
    return load_toml(CONTRACT_PATH), load_toml(MATURITY_PATH)


def version_pin_problems(contract: dict[str, Any]) -> list[str]:
    """Check that every CUDA-Q contract in this repository pins the same versions.

    Two contracts describe CUDA-Q: the export contract and this parity matrix.
    If they disagree about which CUDA-Q they describe, a reader comparing an
    export failure against a parity row is comparing two different products.
    """
    problems: list[str] = []
    if not EXPORT_CONTRACT_PATH.is_file():
        return [f"missing file: {EXPORT_CONTRACT_PATH.relative_to(REPO_ROOT)}"]
    export = load_toml(EXPORT_CONTRACT_PATH)
    if tuple(contract.get("cudaq_versions", ())) != tuple(
        export.get("cudaq_versions", ())
    ):
        problems.append(
            "cudaq_versions must match contracts/cudaq-export-contract.toml: "
            f"{list(contract.get('cudaq_versions', ()))} != "
            f"{list(export.get('cudaq_versions', ()))}"
        )
    if not GAP_MATRIX_PATH.is_file():
        return problems + [f"missing file: {GAP_MATRIX_PATH.relative_to(REPO_ROOT)}"]
    gap_matrix = load_toml(GAP_MATRIX_PATH)
    frameworks = {
        framework.get("name"): framework
        for framework in gap_matrix.get("frameworks", ())
        if isinstance(framework, dict)
    }
    cudaq = frameworks.get("cudaq")
    if cudaq is None:
        problems.append(
            "contracts/interop-capability-gap-matrix.toml no longer declares a "
            "'cudaq' framework, so this matrix has no adapter-level counterpart"
        )
    elif cudaq.get("contract") != "contracts/cudaq-export-contract.toml":
        problems.append(
            "the gap matrix 'cudaq' framework must point at "
            "contracts/cudaq-export-contract.toml, not "
            f"{cudaq.get('contract')!r}"
        )
    return problems


def probe_problems(contract: dict[str, Any]) -> list[str]:
    """Check that every probe the baseline names exists and is not oversold.

    A probe recorded at ``status = "runnable"`` is a claim that the script starts
    and emits its schema. That claim is only worth anything if the file is
    present, so a missing path fails closed here. A ``measured`` status would
    need a landed payload, and no such payload exists, so only the two declared
    statuses are accepted.
    """
    problems: list[str] = []
    baseline = contract.get("baseline", {})
    probes = baseline.get("probes", ())
    if not probes:
        problems.append(
            "baseline.probes must name at least one probe, or the baseline is a "
            "survey with no instrument"
        )
    for probe in probes:
        path_text = probe.get("path")
        if not path_text:
            problems.append("a baseline probe entry has no path")
            continue
        if probe.get("status") not in PROBE_STATUS_ORDER:
            problems.append(
                f"baseline probe {path_text!r}: status is {probe.get('status')!r}, "
                f"allowed values are {list(PROBE_STATUS_ORDER)}"
            )
        if not probe.get("measures"):
            problems.append(
                f"baseline probe {path_text!r}: no measures, so a reader cannot "
                "tell what the probe establishes"
            )
        if not (REPO_ROOT / path_text).is_file():
            problems.append(
                f"baseline probe {path_text!r} matches no file; a probe that does "
                "not exist cannot be runnable"
            )
        if probe.get("status") != "measured":
            continue
        # `measured` is the stronger claim, so it has to carry the artifact that
        # justifies it. A status word with no payload behind it is the failure
        # mode this field exists to prevent.
        for field in ("payload", "report"):
            artifact = probe.get(field)
            if not artifact:
                problems.append(
                    f"baseline probe {path_text!r}: status is 'measured' but no "
                    f"{field} names the evidence"
                )
            elif not (REPO_ROOT / artifact).is_file():
                problems.append(
                    f"baseline probe {path_text!r}: {field} {artifact!r} matches no "
                    "file, so the measured status rests on nothing"
                )
    return problems


def _row_maturity_refs(row: dict[str, Any]) -> list[str]:
    """Return the registry entries a row names, in contract order.

    A row names one entry through ``maturity_ref`` or several through
    ``maturity_refs``. Both forms are read here so the validator and the
    renderer cannot disagree about which entries a row claims.
    """
    multiple = row.get("maturity_refs")
    if multiple is not None:
        return list(multiple)
    single = row.get("maturity_ref")
    return [] if single is None else [single]


def surface_ownership_problems(contract: dict[str, Any]) -> list[str]:
    """Check the surface ownership table against the domain inventories.

    A domain's ``cudaq_surface`` list is an inventory of the surface a user
    meets, and an inventory is not an attribution: entries belonging to another
    CUDA-Q component appear in it. ``baseline.surface_ownership`` supplies that
    attribution. The table is only worth having while it explains the inventory
    it claims to, so every entry must match one surface item verbatim and
    exactly, name a declared owner, and state the consequence for the row it
    feeds.
    """
    problems: list[str] = []
    table = contract.get("baseline", {}).get("surface_ownership", {})
    if not table:
        problems.append(
            "baseline.surface_ownership must attribute the surface items that "
            "belong to a CUDA-Q component other than the one this domain compares"
        )
        return problems

    owners = tuple(table.get("owners", ()))
    if not table.get("rule"):
        problems.append("baseline.surface_ownership must state its rule")
    if not owners:
        problems.append("baseline.surface_ownership must declare the component owners")
    default_owner = table.get("default_owner")
    if default_owner not in owners:
        problems.append(
            f"baseline.surface_ownership.default_owner is {default_owner!r}, which is "
            f"not one of the declared owners {list(owners)}"
        )

    inventories: dict[str, list[str]] = {}
    for domain in contract.get("domains", ()):
        for item in domain.get("cudaq_surface", ()):
            inventories.setdefault(item, []).append(domain.get("id", "<unnamed>"))

    for entry in table.get("items", ()):
        item = entry.get("item")
        if not item:
            problems.append("a baseline.surface_ownership entry names no item")
            continue
        matches = inventories.get(item, [])
        if len(matches) != 1:
            problems.append(
                f"baseline.surface_ownership item {item!r} matches {len(matches)} "
                "domain surface lists; an attribution must match one inventory entry "
                "verbatim and exactly once"
            )
            continue
        if entry.get("owner") not in owners:
            problems.append(
                f"baseline.surface_ownership item {item!r}: owner "
                f"{entry.get('owner')!r} is not one of the declared owners "
                f"{list(owners)}"
            )
        if not entry.get("consequence"):
            problems.append(
                f"baseline.surface_ownership item {item!r}: no consequence, so a "
                "reader cannot tell what the ownership means for the row it feeds"
            )
    return problems


def version_provenance_problems(contract: dict[str, Any]) -> list[str]:
    """Check that the component release line is recorded and not overread.

    ``cudaq_versions`` pins CUDA-Q core. The QEC component ships on its own
    release line, so a QEC row is only as strong as the component version it was
    read at, and a reader must not infer that the core pin reaches it. The
    failure this check prevents is a contract that quietly assumes the pin does:
    a pin that also appears on the component release line means a
    correspondence exists and must be recorded, and a recorded correspondence
    across two lines that do not meet is a claim nothing supports.
    """
    problems: list[str] = []
    provenance = contract.get("baseline", {}).get("version_provenance", {})
    if not provenance:
        problems.append(
            "baseline.version_provenance must record the release line of the "
            "component the quantum_error_correction rows were read at"
        )
        return problems

    for field in (
        "pinned_component",
        "component",
        "component_version_recorded",
        "component_source",
        "provenance_limit",
    ):
        if not provenance.get(field):
            problems.append(f"baseline.version_provenance.{field} is required")

    line = tuple(provenance.get("component_release_line", ()))
    if not line:
        problems.append(
            "baseline.version_provenance.component_release_line is required, or the "
            "recorded component version is unanchored"
        )
    recorded = provenance.get("component_version_recorded")
    if line and recorded and recorded not in line:
        problems.append(
            f"baseline.version_provenance.component_version_recorded {recorded!r} is "
            f"not on the recorded release line {list(line)}"
        )

    pinned = tuple(contract.get("cudaq_versions", ()))
    overlap = sorted(version for version in pinned if version in line)
    mapping = provenance.get("version_mapping", {})
    if overlap and not mapping:
        problems.append(
            f"cudaq_versions {overlap} also appear on the component release line, so a "
            "correspondence exists; record it in "
            "baseline.version_provenance.version_mapping"
        )
    if not overlap and mapping:
        problems.append(
            f"baseline.version_provenance.version_mapping claims a correspondence "
            f"between the pins {list(pinned)} and the component release line "
            f"{list(line)}, but the two lines have no version in common"
        )
    for core_version, component_versions in mapping.items():
        if core_version not in pinned:
            problems.append(
                f"baseline.version_provenance.version_mapping names {core_version!r}, "
                f"which is not one of the pinned versions {list(pinned)}"
            )
        for component_version in component_versions:
            if component_version not in line:
                problems.append(
                    "baseline.version_provenance.version_mapping names component "
                    f"version {component_version!r}, which is not on the recorded "
                    "release line"
                )
    return problems


def validate_contract(contract: dict[str, Any], maturity: dict[str, Any]) -> list[str]:
    """Return the list of violations. An empty list means the contract is valid."""
    problems: list[str] = []

    if contract.get("schema") != EXPECTED_SCHEMA:
        problems.append(
            f"schema is {contract.get('schema')!r}, expected {EXPECTED_SCHEMA!r}"
        )

    for field in ("status_values", "priority_values", "dependency_classes"):
        declared = tuple(contract.get(field, ()))
        expected = {
            "status_values": STATUS_ORDER,
            "priority_values": PRIORITY_ORDER,
            "dependency_classes": DEPENDENCY_ORDER,
        }[field]
        if declared != expected:
            problems.append(
                f"{field} must be exactly {list(expected)}, got {list(declared)}"
            )

    known_capabilities = set(maturity.get("capabilities", {}))
    if not known_capabilities:
        problems.append(
            "capability-maturity.toml declares no capabilities to validate against"
        )

    domains = contract.get("domains", ())
    domain_ids = [domain.get("id") for domain in domains]
    if domain_ids != list(contract.get("domain_order", ())):
        problems.append(
            "domain_order must list every [[domains]] id exactly once and in order; "
            f"got {domain_ids}"
        )

    seen_rows: set[str] = set()
    for domain in domains:
        domain_id = domain.get("id", "<unnamed>")
        rows = domain.get("capabilities", ())
        if not rows:
            problems.append(f"domain {domain_id!r} declares no capabilities")
        for row in rows:
            row_id = row.get("id", "<unnamed>")
            where = f"{domain_id}/{row_id}"
            if row_id in seen_rows:
                problems.append(f"{where}: duplicate capability id")
            seen_rows.add(row_id)

            for field, allowed in (
                ("status", contract.get("status_values", ())),
                ("priority", contract.get("priority_values", ())),
                ("dependency_class", contract.get("dependency_classes", ())),
            ):
                if field not in row:
                    problems.append(f"{where}: missing required field {field!r}")
                elif row[field] not in allowed:
                    problems.append(
                        f"{where}: {field} is {row[field]!r}, "
                        f"allowed values are {list(allowed)}"
                    )

            if not row.get("reason"):
                problems.append(
                    f"{where}: a row without a reason is a plan, not parity"
                )

            maturity_refs = _row_maturity_refs(row)
            if (
                row.get("maturity_refs") is not None
                and row.get("maturity_ref") is not None
            ):
                problems.append(
                    f"{where}: names both maturity_ref and maturity_refs, and a row "
                    "names its registry entries through one form or the other"
                )
            if len(set(maturity_refs)) != len(maturity_refs):
                problems.append(
                    f"{where}: a maturity reference is named twice, so the row claims "
                    "one registry entry as two"
                )
            for maturity_ref in maturity_refs:
                if maturity_ref not in known_capabilities:
                    problems.append(
                        f"{where}: maturity_ref {maturity_ref!r} is not declared in "
                        "capability-maturity.toml"
                    )
            if row.get("status") == "supported" and not maturity_refs:
                problems.append(
                    f"{where}: 'supported' requires a maturity_ref, because a parity "
                    "claim with no registry entry has no owner and no evidence set"
                )

            if row.get("priority") == "excluded" and row.get("status") != (
                "out_of_scope"
            ):
                problems.append(
                    f"{where}: 'excluded' priority requires 'out_of_scope' status"
                )

            # Evidence is required per row and may be declared once per domain.
            evidence = row.get("evidence", domain.get("evidence", ()))
            if not evidence:
                problems.append(
                    f"{where}: no evidence, and the domain declares no default evidence"
                )
            for item in evidence:
                if item.startswith(EVIDENCE_SEARCH_PREFIX):
                    if len(item) <= len(EVIDENCE_SEARCH_PREFIX):
                        problems.append(
                            f"{where}: an evidence search token must describe "
                            "what was searched"
                        )
                    continue
                if not (REPO_ROOT / item).exists():
                    problems.append(f"{where}: evidence path does not exist: {item}")

    if not contract.get("baseline", {}).get("instrument"):
        problems.append("baseline.instrument must name the recorded CUDA-Q survey")

    problems.extend(probe_problems(contract))

    problems.extend(surface_ownership_problems(contract))

    problems.extend(version_provenance_problems(contract))

    problems.extend(version_pin_problems(contract))

    return problems


def _scoreboard(contract: dict[str, Any]) -> list[str]:
    rows = [
        (domain, row)
        for domain in contract["domains"]
        for row in domain.get("capabilities", ())
    ]
    lines: list[str] = []

    lines.append("### Status by domain")
    lines.append("")
    lines.append("| Domain | " + " | ".join(STATUS_ORDER) + " | Total |")
    lines.append("| --- | " + " | ".join("---" for _ in STATUS_ORDER) + " | --- |")
    for domain in contract["domains"]:
        counts = Counter(row["status"] for row in domain["capabilities"])
        cells = " | ".join(str(counts.get(status, 0)) for status in STATUS_ORDER)
        lines.append(f"| {domain['id']} | {cells} | {len(domain['capabilities'])} |")
    totals = Counter(row["status"] for _, row in rows)
    cells = " | ".join(str(totals.get(status, 0)) for status in STATUS_ORDER)
    lines.append(f"| **Total** | {cells} | {len(rows)} |")

    lines.append("")
    lines.append("### Dependency class of every open gap")
    lines.append("")
    lines.append(
        "The replacement battlefield is the set of capabilities where the CUDA-Q "
        "implementation sits on an NVIDIA-proprietary component. Each such capability "
        "is a gap FlagQuantum must close with its own kernel or with a FlagOS-family "
        "component, not by depending on the NVIDIA original."
    )
    lines.append("")
    lines.append("| Dependency class | Open gaps | Closed | Total |")
    lines.append("| --- | --- | --- | --- |")
    for dependency in DEPENDENCY_ORDER:
        selected = [row for _, row in rows if row["dependency_class"] == dependency]
        open_gaps = [
            row for row in selected if row["status"] in ("unsupported", "partial")
        ]
        lines.append(
            f"| {dependency} | {len(open_gaps)} | {len(selected) - len(open_gaps)} | "
            f"{len(selected)} |"
        )

    lines.append("")
    lines.append("### Next work, by priority")
    lines.append("")
    for priority in PRIORITY_ORDER:
        selected = [
            (domain, row)
            for domain, row in rows
            if row["priority"] == priority
            and row["status"] in ("unsupported", "partial")
        ]
        if not selected:
            continue
        lines.append(f"**{priority}** ({len(selected)} open)")
        lines.append("")
        for domain, row in selected:
            lines.append(f"- `{row['id']}` ({domain['id']}): {row['reason']}")
        lines.append("")

    return lines


def render_document(contract: dict[str, Any]) -> str:
    baseline = contract.get("baseline", {})
    lines: list[str] = []
    lines.append(GENERATED_BANNER)
    lines.append("")
    lines.append("# CUDA-Q parity matrix")
    lines.append("")
    lines.append(
        "This scoreboard is generated from `contracts/cudaq-parity-matrix.toml`. It "
        "compares the CUDA-Q capability baseline against FlagQuantum. FlagQuantum "
        "maturity levels, owners, limitations, and evidence paths are read from "
        "`capability-maturity.toml` and are not restated here; a row whose registry "
        "column reads `none` has no registered maturity entry."
    )
    lines.append("")
    lines.append(f"- CUDA-Q baseline versions: {', '.join(contract['cudaq_versions'])}")
    provenance = baseline.get("version_provenance", {})
    if provenance:
        lines.append(f"- Pinned component: {provenance.get('pinned_component')}")
        lines.append(f"- Baseline component: {provenance.get('component')}")
        lines.append(
            "- Component release line: "
            + ", ".join(provenance.get("component_release_line", ()))
        )
        lines.append(
            "- Component version the `quantum_error_correction` rows were read at: "
            f"{provenance.get('component_version_recorded')}"
        )
        lines.append(f"- Component release index: {provenance.get('component_source')}")
        lines.append("")
        lines.append(provenance.get("rule", ""))
        lines.append("")
        lines.append(f"Provenance limit: {provenance.get('provenance_limit')}")
    lines.append(f"- Baseline survey: `{baseline.get('instrument', 'unrecorded')}`")
    lines.append(f"- Capture method: {baseline.get('capture_method', 'unrecorded')}")
    lines.append(f"- Scope: {baseline.get('scope', 'unrecorded')}")
    probes = baseline.get("probes", ())
    if probes:
        lines.append("")
        lines.append("Baseline probes:")
        lines.append("")
        lines.append(contract.get("baseline", {}).get("probe_rule", ""))
        lines.append("")
        lines.append("| Probe | Status | What it measures |")
        lines.append("| --- | --- | --- |")
        for probe in probes:
            lines.append(
                f"| `{probe['path']}` | {probe['status']} | {probe['measures']} |"
            )
        for probe in probes:
            if probe.get("first_capture"):
                lines.append("")
                lines.append(
                    f"First capture, `{probe['path']}`: {probe['first_capture']}"
                )
            if probe.get("payload"):
                lines.append("")
                lines.append(f"Landed payload: `{probe['payload']}`")
            if probe.get("report"):
                lines.append("")
                lines.append(f"Reading of that payload: `{probe['report']}`")
    related = contract.get("related_contracts", ())
    if related:
        lines.append("")
        lines.append("Related CUDA-Q contracts:")
        lines.append("")
        for path in related:
            lines.append(f"- `{path}`")
        lines.append("")
        lines.append(contract.get("related_contract_rule", ""))
    ownership = baseline.get("surface_ownership", {})
    ownership_items = ownership.get("items", ())
    if ownership_items:
        lines.append("")
        lines.append("Baseline component ownership:")
        lines.append("")
        lines.append(ownership.get("rule", ""))
        lines.append("")
        lines.append("| CUDA-Q surface item | Owning component |")
        lines.append("| --- | --- |")
        for entry in ownership_items:
            lines.append(f"| {entry['item']} | `{entry['owner']}` |")
        lines.append("")
        for entry in ownership_items:
            lines.append(
                f"- `{entry['owner']}`, {entry['item']}: {entry['consequence']}"
            )
    lines.append("")
    for item in baseline.get("limitations", {}).get("items", ()):
        lines.append(f"- Limitation: {item}")
    lines.append("")
    lines.append(
        "No row in this document is a performance comparison or a scalability claim."
    )
    lines.append("")
    lines.extend(_scoreboard(contract))
    lines.append("### Capability detail")
    lines.append("")
    for domain in contract["domains"]:
        lines.append(f"#### {domain['title']}")
        lines.append("")
        lines.append(f"Domain id: `{domain['id']}`")
        lines.append("")
        lines.append(f"CUDA-Q surface: {', '.join(domain['cudaq_surface'])}")
        lines.append("")
        lines.append(
            "| Capability | CUDA-Q baseline | Status | Priority | Dependency class | "
            "FlagQuantum maturity | Reason |"
        )
        lines.append("| --- | --- | --- | --- | --- | --- | --- |")
        for row in domain["capabilities"]:
            maturity_refs = _row_maturity_refs(row)
            maturity_cell = (
                ", ".join(f"`{ref}`" for ref in maturity_refs)
                if maturity_refs
                else "none"
            )
            reason_cell = row["reason"]
            if row.get("baseline_gap"):
                reason_cell = (
                    f"{reason_cell} <br><br>Narrower scope at this status: "
                    f"{row['baseline_gap']}"
                )
            lines.append(
                f"| `{row['id']}` | {row['cudaq']} | {row['status']} | "
                f"{row['priority']} | {row['dependency_class']} | "
                f"{maturity_cell} | {reason_cell} |"
            )
        lines.append("")
        lines.append("Evidence:")
        lines.append("")
        for item in domain.get("evidence", ()):
            if item.startswith(EVIDENCE_SEARCH_PREFIX):
                searched = item[len(EVIDENCE_SEARCH_PREFIX) :]
                lines.append(f"- domain default, negative search: {searched}")
            else:
                lines.append(f"- domain default: `{item}`")
        overrides = [
            f"- `{row['id']}` override: "
            + ", ".join(f"`{item}`" for item in row["evidence"])
            for row in domain["capabilities"]
            if row.get("evidence")
        ]
        if overrides:
            lines.append("")
            lines.extend(overrides)
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "fail if the generated document differs from the contract "
            "instead of writing it"
        ),
    )
    args = parser.parse_args(argv)

    try:
        contract, maturity = load_inputs()
    except ContractError as error:
        print(f"parity-matrix: {error}", file=sys.stderr)
        return 2

    problems = validate_contract(contract, maturity)
    if problems:
        print("parity-matrix: contract violations:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 2

    rendered = render_document(contract)

    if args.check:
        if not OUTPUT_PATH.is_file():
            print(
                f"parity-matrix: {OUTPUT_PATH.relative_to(REPO_ROOT)} is missing; "
                "run tools/parity_matrix.py",
                file=sys.stderr,
            )
            return 2
        if OUTPUT_PATH.read_text(encoding="utf-8") != rendered:
            print(
                f"parity-matrix: {OUTPUT_PATH.relative_to(REPO_ROOT)} is stale; "
                "run tools/parity_matrix.py and commit the regenerated document",
                file=sys.stderr,
            )
            return 2
        print("parity-matrix: contract valid and document current")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    rows = sum(len(domain["capabilities"]) for domain in contract["domains"])
    print(
        f"parity-matrix: wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} "
        f"({len(contract['domains'])} domains, {rows} capabilities)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
