"""Generate and validate the CUDA-Q parity scoreboard.

The parity matrix contract ``contracts/cudaq-parity-matrix.toml`` is the source
of truth. This tool validates it against the repository and renders
``docs/reference/CUDAQ_PARITY_MATRIX.md`` from it, so the published scoreboard
cannot drift from the contract.

Validation is fail-closed. An unknown status, priority, or dependency class; a
``maturity_ref`` that is absent from ``capability-maturity.toml``; a `supported`
row with no registry entry; a missing or malformed evidence item; or a stale
generated document all exit non-zero.

Evidence is declared per row and falls back to the domain default. An item is
either a repository-relative path, which must exist, or a ``search:`` token
recording the negative search that established an absence.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python 3.10 compatibility
    import tomli as tomllib

REPO_ROOT = Path(__file__).resolve().parent.parent
CONTRACT_PATH = REPO_ROOT / "contracts" / "cudaq-parity-matrix.toml"
MATURITY_PATH = REPO_ROOT / "capability-maturity.toml"
EXPORT_CONTRACT_PATH = REPO_ROOT / "contracts" / "cudaq-export-contract.toml"
GAP_MATRIX_PATH = REPO_ROOT / "contracts" / "interop-capability-gap-matrix.toml"
OUTPUT_PATH = REPO_ROOT / "docs" / "reference" / "CUDAQ_PARITY_MATRIX.md"

EXPECTED_SCHEMA = "flagquantum_cudaq_parity_matrix_v1"
GENERATED_BANNER = "<!-- Generated by tools/parity_matrix.py. Do not edit by hand. -->"
EVIDENCE_SEARCH_PREFIX = "search:"

STATUS_ORDER = ("supported", "partial", "unsupported", "out_of_scope")
PRIORITY_ORDER = ("now", "next", "later", "excluded")
DEPENDENCY_ORDER = (
    "A_nvidia_proprietary",
    "B_open_neutral",
    "C_flagos_replacement",
    "none",
)
PROBE_STATUS_ORDER = ("runnable", "measured")


class ContractError(Exception):
    """A parity contract violates a rule the repository depends on."""


def load_toml(path: Path) -> dict[str, Any]:
    """Load a TOML document by text, so the parser is not the thing under test."""
    return tomllib.loads(path.read_text(encoding="utf-8"))


def load_inputs() -> tuple[dict[str, Any], dict[str, Any]]:
    """Return the parity contract and the capability registry it validates against."""
    for path in (CONTRACT_PATH, MATURITY_PATH):
        if not path.is_file():
            raise ContractError(f"missing file: {path.relative_to(REPO_ROOT)}")
    return load_toml(CONTRACT_PATH), load_toml(MATURITY_PATH)


def version_pin_problems(contract: dict[str, Any]) -> list[str]:
    """Check that every CUDA-Q contract in this repository pins the same versions.

    Two contracts describe CUDA-Q: the export contract and this parity matrix.
    If they disagree about which CUDA-Q they describe, a reader comparing an
    export failure against a parity row is comparing two different products.
    """
    problems: list[str] = []
    if not EXPORT_CONTRACT_PATH.is_file():
        return [f"missing file: {EXPORT_CONTRACT_PATH.relative_to(REPO_ROOT)}"]
    export = load_toml(EXPORT_CONTRACT_PATH)
    if tuple(contract.get("cudaq_versions", ())) != tuple(
        export.get("cudaq_versions", ())
    ):
        problems.append(
            "cudaq_versions must match contracts/cudaq-export-contract.toml: "
            f"{list(contract.get('cudaq_versions', ()))} != "
            f"{list(export.get('cudaq_versions', ()))}"
        )
    if not GAP_MATRIX_PATH.is_file():
        return problems + [f"missing file: {GAP_MATRIX_PATH.relative_to(REPO_ROOT)}"]
    gap_matrix = load_toml(GAP_MATRIX_PATH)
    frameworks = {
        framework.get("name"): framework
        for framework in gap_matrix.get("frameworks", ())
        if isinstance(framework, dict)
    }
    cudaq = frameworks.get("cudaq")
    if cudaq is None:
        problems.append(
            "contracts/interop-capability-gap-matrix.toml no longer declares a "
            "'cudaq' framework, so this matrix has no adapter-level counterpart"
        )
    elif cudaq.get("contract") != "contracts/cudaq-export-contract.toml":
        problems.append(
            "the gap matrix 'cudaq' framework must point at "
            "contracts/cudaq-export-contract.toml, not "
            f"{cudaq.get('contract')!r}"
        )
    return problems


def probe_problems(contract: dict[str, Any]) -> list[str]:
    """Check that every probe the baseline names exists and is not oversold.

    A probe recorded at ``status = "runnable"`` is a claim that the script starts
    and emits its schema. That claim is only worth anything if the file is
    present, so a missing path fails closed here. A ``measured`` status would
    need a landed payload, and no such payload exists, so only the two declared
    statuses are accepted.
    """
    problems: list[str] = []
    baseline = contract.get("baseline", {})
    probes = baseline.get("probes", ())
    if not probes:
        problems.append(
            "baseline.probes must name at least one probe, or the baseline is a "
            "survey with no instrument"
        )
    for probe in probes:
        path_text = probe.get("path")
        if not path_text:
            problems.append("a baseline probe entry has no path")
            continue
        if probe.get("status") not in PROBE_STATUS_ORDER:
            problems.append(
                f"baseline probe {path_text!r}: status is {probe.get('status')!r}, "
                f"allowed values are {list(PROBE_STATUS_ORDER)}"
            )
        if not probe.get("measures"):
            problems.append(
                f"baseline probe {path_text!r}: no measures, so a reader cannot "
                "tell what the probe establishes"
            )
        if not (REPO_ROOT / path_text).is_file():
            problems.append(
                f"baseline probe {path_text!r} matches no file; a probe that does "
                "not exist cannot be runnable"
            )
    return problems


def validate_contract(contract: dict[str, Any], maturity: dict[str, Any]) -> list[str]:
    """Return the list of violations. An empty list means the contract is valid."""
    problems: list[str] = []

    if contract.get("schema") != EXPECTED_SCHEMA:
        problems.append(
            f"schema is {contract.get('schema')!r}, expected {EXPECTED_SCHEMA!r}"
        )

    for field in ("status_values", "priority_values", "dependency_classes"):
        declared = tuple(contract.get(field, ()))
        expected = {
            "status_values": STATUS_ORDER,
            "priority_values": PRIORITY_ORDER,
            "dependency_classes": DEPENDENCY_ORDER,
        }[field]
        if declared != expected:
            problems.append(
                f"{field} must be exactly {list(expected)}, got {list(declared)}"
            )

    known_capabilities = set(maturity.get("capabilities", {}))
    if not known_capabilities:
        problems.append(
            "capability-maturity.toml declares no capabilities to validate against"
        )

    domains = contract.get("domains", ())
    domain_ids = [domain.get("id") for domain in domains]
    if domain_ids != list(contract.get("domain_order", ())):
        problems.append(
            "domain_order must list every [[domains]] id exactly once and in order; "
            f"got {domain_ids}"
        )

    seen_rows: set[str] = set()
    for domain in domains:
        domain_id = domain.get("id", "<unnamed>")
        rows = domain.get("capabilities", ())
        if not rows:
            problems.append(f"domain {domain_id!r} declares no capabilities")
        for row in rows:
            row_id = row.get("id", "<unnamed>")
            where = f"{domain_id}/{row_id}"
            if row_id in seen_rows:
                problems.append(f"{where}: duplicate capability id")
            seen_rows.add(row_id)

            for field, allowed in (
                ("status", contract.get("status_values", ())),
                ("priority", contract.get("priority_values", ())),
                ("dependency_class", contract.get("dependency_classes", ())),
            ):
                if field not in row:
                    problems.append(f"{where}: missing required field {field!r}")
                elif row[field] not in allowed:
                    problems.append(
                        f"{where}: {field} is {row[field]!r}, "
                        f"allowed values are {list(allowed)}"
                    )

            if not row.get("reason"):
                problems.append(
                    f"{where}: a row without a reason is a plan, not parity"
                )

            maturity_ref = row.get("maturity_ref")
            if maturity_ref is not None and maturity_ref not in known_capabilities:
                problems.append(
                    f"{where}: maturity_ref {maturity_ref!r} is not declared in "
                    "capability-maturity.toml"
                )
            if row.get("status") == "supported" and maturity_ref is None:
                problems.append(
                    f"{where}: 'supported' requires a maturity_ref, because a parity "
                    "claim with no registry entry has no owner and no evidence set"
                )

            if row.get("priority") == "excluded" and row.get("status") != (
                "out_of_scope"
            ):
                problems.append(
                    f"{where}: 'excluded' priority requires 'out_of_scope' status"
                )

            # Evidence is required per row and may be declared once per domain.
            evidence = row.get("evidence", domain.get("evidence", ()))
            if not evidence:
                problems.append(
                    f"{where}: no evidence, and the domain declares no default evidence"
                )
            for item in evidence:
                if item.startswith(EVIDENCE_SEARCH_PREFIX):
                    if len(item) <= len(EVIDENCE_SEARCH_PREFIX):
                        problems.append(
                            f"{where}: an evidence search token must describe "
                            "what was searched"
                        )
                    continue
                if not (REPO_ROOT / item).exists():
                    problems.append(f"{where}: evidence path does not exist: {item}")

    if not contract.get("baseline", {}).get("instrument"):
        problems.append("baseline.instrument must name the recorded CUDA-Q survey")

    problems.extend(probe_problems(contract))

    problems.extend(version_pin_problems(contract))

    return problems


def _scoreboard(contract: dict[str, Any]) -> list[str]:
    rows = [
        (domain, row)
        for domain in contract["domains"]
        for row in domain.get("capabilities", ())
    ]
    lines: list[str] = []

    lines.append("### Status by domain")
    lines.append("")
    lines.append("| Domain | " + " | ".join(STATUS_ORDER) + " | Total |")
    lines.append("| --- | " + " | ".join("---" for _ in STATUS_ORDER) + " | --- |")
    for domain in contract["domains"]:
        counts = Counter(row["status"] for row in domain["capabilities"])
        cells = " | ".join(str(counts.get(status, 0)) for status in STATUS_ORDER)
        lines.append(f"| {domain['id']} | {cells} | {len(domain['capabilities'])} |")
    totals = Counter(row["status"] for _, row in rows)
    cells = " | ".join(str(totals.get(status, 0)) for status in STATUS_ORDER)
    lines.append(f"| **Total** | {cells} | {len(rows)} |")

    lines.append("")
    lines.append("### Dependency class of every open gap")
    lines.append("")
    lines.append(
        "The replacement battlefield is the set of capabilities where the CUDA-Q "
        "implementation sits on an NVIDIA-proprietary component. Each such capability "
        "is a gap FlagQuantum must close with its own kernel or with a FlagOS-family "
        "component, not by depending on the NVIDIA original."
    )
    lines.append("")
    lines.append("| Dependency class | Open gaps | Closed | Total |")
    lines.append("| --- | --- | --- | --- |")
    for dependency in DEPENDENCY_ORDER:
        selected = [row for _, row in rows if row["dependency_class"] == dependency]
        open_gaps = [
            row for row in selected if row["status"] in ("unsupported", "partial")
        ]
        lines.append(
            f"| {dependency} | {len(open_gaps)} | {len(selected) - len(open_gaps)} | "
            f"{len(selected)} |"
        )

    lines.append("")
    lines.append("### Next work, by priority")
    lines.append("")
    for priority in PRIORITY_ORDER:
        selected = [
            (domain, row)
            for domain, row in rows
            if row["priority"] == priority
            and row["status"] in ("unsupported", "partial")
        ]
        if not selected:
            continue
        lines.append(f"**{priority}** ({len(selected)} open)")
        lines.append("")
        for domain, row in selected:
            lines.append(f"- `{row['id']}` ({domain['id']}): {row['reason']}")
        lines.append("")

    return lines


def render_document(contract: dict[str, Any]) -> str:
    baseline = contract.get("baseline", {})
    lines: list[str] = []
    lines.append(GENERATED_BANNER)
    lines.append("")
    lines.append("# CUDA-Q parity matrix")
    lines.append("")
    lines.append(
        "This scoreboard is generated from `contracts/cudaq-parity-matrix.toml`. It "
        "compares the CUDA-Q capability baseline against FlagQuantum. FlagQuantum "
        "maturity levels, owners, limitations, and evidence paths are read from "
        "`capability-maturity.toml` and are not restated here; a row whose registry "
        "column reads `none` has no registered maturity entry."
    )
    lines.append("")
    lines.append(f"- CUDA-Q baseline versions: {', '.join(contract['cudaq_versions'])}")
    lines.append(f"- Baseline survey: `{baseline.get('instrument', 'unrecorded')}`")
    lines.append(f"- Capture method: {baseline.get('capture_method', 'unrecorded')}")
    lines.append(f"- Scope: {baseline.get('scope', 'unrecorded')}")
    probes = baseline.get("probes", ())
    if probes:
        lines.append("")
        lines.append("Baseline probes:")
        lines.append("")
        lines.append(contract.get("baseline", {}).get("probe_rule", ""))
        lines.append("")
        lines.append("| Probe | Status | What it measures |")
        lines.append("| --- | --- | --- |")
        for probe in probes:
            lines.append(
                f"| `{probe['path']}` | {probe['status']} | {probe['measures']} |"
            )
        for probe in probes:
            if probe.get("first_capture"):
                lines.append("")
                lines.append(f"First capture, `{probe['path']}`: {probe['first_capture']}")
    related = contract.get("related_contracts", ())
    if related:
        lines.append("")
        lines.append("Related CUDA-Q contracts:")
        lines.append("")
        for path in related:
            lines.append(f"- `{path}`")
        lines.append("")
        lines.append(contract.get("related_contract_rule", ""))
    lines.append("")
    for item in baseline.get("limitations", {}).get("items", ()):
        lines.append(f"- Limitation: {item}")
    lines.append("")
    lines.append(
        "No row in this document is a performance comparison or a scalability claim."
    )
    lines.append("")
    lines.extend(_scoreboard(contract))
    lines.append("### Capability detail")
    lines.append("")
    for domain in contract["domains"]:
        lines.append(f"#### {domain['title']}")
        lines.append("")
        lines.append(f"Domain id: `{domain['id']}`")
        lines.append("")
        lines.append(f"CUDA-Q surface: {', '.join(domain['cudaq_surface'])}")
        lines.append("")
        lines.append(
            "| Capability | CUDA-Q baseline | Status | Priority | Dependency class | "
            "FlagQuantum maturity | Reason |"
        )
        lines.append("| --- | --- | --- | --- | --- | --- | --- |")
        for row in domain["capabilities"]:
            maturity_cell = (
                f"`{row['maturity_ref']}`" if row.get("maturity_ref") else "none"
            )
            reason_cell = row["reason"]
            if row.get("baseline_gap"):
                reason_cell = (
                    f"{reason_cell} <br><br>Narrower scope at this status: "
                    f"{row['baseline_gap']}"
                )
            lines.append(
                f"| `{row['id']}` | {row['cudaq']} | {row['status']} | "
                f"{row['priority']} | {row['dependency_class']} | "
                f"{maturity_cell} | {reason_cell} |"
            )
        lines.append("")
        lines.append("Evidence:")
        lines.append("")
        for item in domain.get("evidence", ()):
            if item.startswith(EVIDENCE_SEARCH_PREFIX):
                searched = item[len(EVIDENCE_SEARCH_PREFIX) :]
                lines.append(f"- domain default, negative search: {searched}")
            else:
                lines.append(f"- domain default: `{item}`")
        overrides = [
            f"- `{row['id']}` override: "
            + ", ".join(f"`{item}`" for item in row["evidence"])
            for row in domain["capabilities"]
            if row.get("evidence")
        ]
        if overrides:
            lines.append("")
            lines.extend(overrides)
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "fail if the generated document differs from the contract "
            "instead of writing it"
        ),
    )
    args = parser.parse_args(argv)

    try:
        contract, maturity = load_inputs()
    except ContractError as error:
        print(f"parity-matrix: {error}", file=sys.stderr)
        return 2

    problems = validate_contract(contract, maturity)
    if problems:
        print("parity-matrix: contract violations:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 2

    rendered = render_document(contract)

    if args.check:
        if not OUTPUT_PATH.is_file():
            print(
                f"parity-matrix: {OUTPUT_PATH.relative_to(REPO_ROOT)} is missing; "
                "run tools/parity_matrix.py",
                file=sys.stderr,
            )
            return 2
        if OUTPUT_PATH.read_text(encoding="utf-8") != rendered:
            print(
                f"parity-matrix: {OUTPUT_PATH.relative_to(REPO_ROOT)} is stale; "
                "run tools/parity_matrix.py and commit the regenerated document",
                file=sys.stderr,
            )
            return 2
        print("parity-matrix: contract valid and document current")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    rows = sum(len(domain["capabilities"]) for domain in contract["domains"])
    print(
        f"parity-matrix: wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} "
        f"({len(contract['domains'])} domains, {rows} capabilities)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
