"""CUDA-Q parity matrix contract guard.

The contract is the source of truth and the published scoreboard is generated
from it, so these tests fail closed on both a contract violation and a stale
generated document.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

from flagquantum.runtime.audit.engine import audit_distributed_scalability
from tools.parity_matrix import (
    CONTRACT_PATH,
    MATURITY_PATH,
    OUTPUT_PATH,
    load_inputs,
    probe_problems,
    render_document,
    surface_ownership_problems,
    validate_contract,
    version_pin_problems,
    version_provenance_problems,
)
from tools.sanitize_public_evidence import sanitize_text

pytestmark = pytest.mark.unit

ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture()
def contract_and_registry() -> tuple[dict, dict]:
    return load_inputs()


@pytest.fixture()
def contract(contract_and_registry: tuple[dict, dict]) -> dict:
    return copy.deepcopy(contract_and_registry[0])


def _first_row(contract: dict) -> dict:
    return contract["domains"][0]["capabilities"][0]


def test_parity_contract_is_valid(contract_and_registry: tuple[dict, dict]) -> None:
    assert validate_contract(*contract_and_registry) == []


def test_parity_contract_points_at_recorded_baseline(
    contract_and_registry: tuple[dict, dict],
) -> None:
    contract, _ = contract_and_registry
    instrument = contract["baseline"]["instrument"]
    assert (ROOT / instrument).is_file()


def test_generated_scoreboard_is_current(
    contract_and_registry: tuple[dict, dict],
) -> None:
    contract, _ = contract_and_registry
    assert OUTPUT_PATH.is_file(), "run tools/parity_matrix.py"
    assert OUTPUT_PATH.read_text(encoding="utf-8") == render_document(contract)


def test_generated_scoreboard_is_marked_generated() -> None:
    first_line = OUTPUT_PATH.read_text(encoding="utf-8").splitlines()[0]
    assert first_line.startswith("<!-- Generated by tools/parity_matrix.py")


def test_every_supported_row_names_a_registry_entry(contract: dict) -> None:
    for domain in contract["domains"]:
        for row in domain["capabilities"]:
            if row["status"] == "supported":
                named = row.get("maturity_refs") or row.get("maturity_ref")
                assert named, f"{row['id']} claims support with no registry entry"


def test_contract_rejects_unknown_status(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    _first_row(contract)["status"] = "strong"
    errors = validate_contract(contract, contract_and_registry[1])
    assert any("status is 'strong'" in error for error in errors)


def test_contract_rejects_unregistered_maturity_reference(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    _first_row(contract)["maturity_ref"] = "not_a_registered_capability"
    errors = validate_contract(contract, contract_and_registry[1])
    assert any(
        "is not declared in capability-maturity.toml" in error for error in errors
    )


def test_contract_rejects_a_supported_row_without_a_registry_entry(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    row = _first_row(contract)
    row["status"] = "supported"
    row.pop("maturity_ref", None)
    errors = validate_contract(contract, contract_and_registry[1])
    assert any("'supported' requires a maturity_ref" in error for error in errors)


def test_contract_rejects_a_missing_evidence_path(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    _first_row(contract)["evidence"] = ["flagquantum/does_not_exist.py"]
    errors = validate_contract(contract, contract_and_registry[1])
    assert any("evidence path does not exist" in error for error in errors)


def test_contract_rejects_an_unexplained_row(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    _first_row(contract).pop("reason", None)
    errors = validate_contract(contract, contract_and_registry[1])
    assert any("without a reason" in error for error in errors)


def test_contract_rejects_excluded_priority_without_out_of_scope_status(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    _first_row(contract)["priority"] = "excluded"
    errors = validate_contract(contract, contract_and_registry[1])
    assert any(
        "'excluded' priority requires 'out_of_scope' status" in error
        for error in errors
    )


def test_contract_rejects_a_domain_without_evidence(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    domain = contract["domains"][0]
    domain.pop("evidence", None)
    for row in domain["capabilities"]:
        row.pop("evidence", None)
    errors = validate_contract(contract, contract_and_registry[1])
    assert any(
        "no evidence, and the domain declares no default evidence" in error
        for error in errors
    )


def test_contract_rejects_a_reordered_domain_list(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    contract["domains"] = list(reversed(contract["domains"]))
    errors = validate_contract(contract, contract_and_registry[1])
    assert any("domain_order must list every" in error for error in errors)


def test_contract_and_registry_are_read_from_the_repository() -> None:
    assert CONTRACT_PATH == ROOT / "contracts" / "cudaq-parity-matrix.toml"
    assert MATURITY_PATH == ROOT / "capability-maturity.toml"


def test_cudaq_contracts_pin_the_same_versions(contract: dict) -> None:
    assert version_pin_problems(contract) == []


def test_the_surface_owner_table_explains_the_inventories_it_attributes(
    contract: dict,
) -> None:
    """The table is only worth having while it matches the surface lists."""

    assert surface_ownership_problems(contract) == []
    items = contract["baseline"]["surface_ownership"]["items"]
    assert items, "no surface item is attributed to another component"
    surfaces = {
        item: domain["id"]
        for domain in contract["domains"]
        for item in domain.get("cudaq_surface", ())
    }
    for entry in items:
        assert surfaces[entry["item"]] == "quantum_error_correction"


def test_surface_ownership_gate_rejects_an_item_matching_no_inventory(
    contract: dict,
) -> None:
    contract["baseline"]["surface_ownership"]["items"][0]["item"] = "not a surface item"
    errors = surface_ownership_problems(contract)
    assert any("matches 0 domain surface lists" in error for error in errors)


def test_surface_ownership_gate_rejects_an_undeclared_owner(contract: dict) -> None:
    contract["baseline"]["surface_ownership"]["items"][0]["owner"] = "cudaq-elsewhere"
    errors = surface_ownership_problems(contract)
    assert any("is not one of the declared owners" in error for error in errors)


def test_surface_ownership_gate_rejects_an_attribution_with_no_consequence(
    contract: dict,
) -> None:
    contract["baseline"]["surface_ownership"]["items"][0].pop("consequence")
    errors = surface_ownership_problems(contract)
    assert any("no consequence" in error for error in errors)


def test_version_provenance_is_recorded_for_the_component(contract: dict) -> None:
    """The QEC rows are read at a component version the core pin does not reach."""

    assert version_provenance_problems(contract) == []
    provenance = contract["baseline"]["version_provenance"]
    line = provenance["component_release_line"]
    assert provenance["component_version_recorded"] in line
    pinned = set(contract["cudaq_versions"])
    assert not pinned & set(line), (
        "the component release line now meets the pin, so the provenance limit in "
        "this contract no longer holds"
    )


def test_version_provenance_gate_rejects_a_recorded_version_off_the_line(
    contract: dict,
) -> None:
    contract["baseline"]["version_provenance"]["component_version_recorded"] = "9.9.9"
    errors = version_provenance_problems(contract)
    assert any("is not on the recorded release line" in error for error in errors)


def test_version_provenance_gate_rejects_a_mapping_across_disjoint_lines(
    contract: dict,
) -> None:
    """A correspondence the release lines do not support is a claim, not a record."""

    contract["baseline"]["version_provenance"]["version_mapping"] = {
        "0.15.1": ["0.8.0"]
    }
    errors = version_provenance_problems(contract)
    assert any("have no version in common" in error for error in errors)


def test_version_provenance_gate_requires_a_mapping_once_the_lines_meet(
    contract: dict,
) -> None:
    contract["cudaq_versions"] = ["0.8.0"]
    errors = version_provenance_problems(contract)
    assert any("record it in" in error for error in errors)


def test_a_row_may_name_more_than_one_registry_entry(contract: dict) -> None:
    """One capability can span two entries; the row says which, and neither drifts."""

    _, maturity = load_inputs()
    known = set(maturity["capabilities"])
    plural = [
        row
        for domain in contract["domains"]
        for row in domain["capabilities"]
        if row.get("maturity_refs")
    ]
    assert plural, "no row exercises the plural form, so it is untested surface"
    for row in plural:
        assert "maturity_ref" not in row
        assert len(row["maturity_refs"]) > 1
        assert set(row["maturity_refs"]) <= known


def test_contract_rejects_a_row_naming_both_registry_forms(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    row = _first_row(contract)
    row["maturity_ref"] = "detector_error_model"
    row["maturity_refs"] = ["detector_error_model"]
    errors = validate_contract(contract, contract_and_registry[1])
    assert any("names both maturity_ref and maturity_refs" in error for error in errors)


def test_contract_rejects_a_repeated_registry_entry(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    row = _first_row(contract)
    row.pop("maturity_ref", None)
    row["maturity_refs"] = ["detector_error_model", "detector_error_model"]
    errors = validate_contract(contract, contract_and_registry[1])
    assert any("named twice" in error for error in errors)


def test_contract_rejects_an_unregistered_maturity_reference_in_the_plural_form(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    row = _first_row(contract)
    row.pop("maturity_ref", None)
    row["maturity_refs"] = ["detector_error_model", "not_a_registered_capability"]
    errors = validate_contract(contract, contract_and_registry[1])
    assert any(
        "'not_a_registered_capability' is not declared in capability-maturity.toml"
        in error
        for error in errors
    )


def test_version_pin_gate_rejects_drift_against_the_export_contract(
    contract: dict,
) -> None:
    contract["cudaq_versions"] = ["9.9.9"]
    errors = version_pin_problems(contract)
    assert any("must match contracts/cudaq-export-contract.toml" in e for e in errors)


def test_ci_gates_the_matrix_and_the_certified_cudaq_lane_agrees(
    contract: dict,
) -> None:
    workflow = (ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    assert "python tools/parity_matrix.py --check" in workflow
    pinned = " ".join(contract["cudaq_versions"])
    assert f'OPTIONAL_VERSIONS: "{pinned}"' in workflow


def _probe(contract: dict, path: str) -> dict:
    for probe in contract["baseline"]["probes"]:
        if probe["path"] == path:
            return probe
    raise AssertionError(f"the contract does not register {path}")


def test_a_measured_probe_must_name_a_landed_payload_and_its_report(
    contract: dict,
) -> None:
    measured = [
        probe
        for probe in contract["baseline"]["probes"]
        if probe["status"] == "measured"
    ]
    assert measured, "no probe is measured, so the promotion path is untested"
    for probe in measured:
        for field in ("payload", "report"):
            artifact = ROOT / probe[field]
            assert artifact.is_file(), f"{probe[field]} is registered but absent"


def test_a_measured_probes_payload_is_sanitized_public_evidence() -> None:
    """Promotion to `measured` must not carry a container hostname into the tree."""

    contract = load_inputs()[0]
    for probe in contract["baseline"]["probes"]:
        if probe["status"] != "measured":
            continue
        payload = ROOT / probe["payload"]
        text = payload.read_text(encoding="utf-8")
        assert sanitize_text(text) == text, (
            f"{probe['payload']} is registered as measured evidence but still "
            "carries an infrastructure identifier"
        )


def test_contract_rejects_a_measured_probe_with_no_payload(contract: dict) -> None:
    probe = _probe(contract, "benchmarks/cudaq_backend_compare.py")
    probe.pop("payload")
    errors = probe_problems(contract)
    assert any(
        "status is 'measured' but no payload names the evidence" in error
        for error in errors
    )


def test_contract_rejects_a_measured_probe_pointing_at_a_missing_payload(
    contract: dict,
) -> None:
    _probe(contract, "benchmarks/cudaq_backend_compare.py")["payload"] = (
        "benchmarks/results/comparison/not_recorded.json"
    )
    errors = probe_problems(contract)
    assert any("the measured status rests on nothing" in error for error in errors)


def test_a_landed_payload_survives_the_benchmark_audit() -> None:
    probe = _probe(load_inputs()[0], "benchmarks/cudaq_backend_compare.py")
    payload = json.loads((ROOT / probe["payload"]).read_text(encoding="utf-8"))
    audit = audit_distributed_scalability(payload)
    assert audit.valid, audit.summary()
    assert not audit.scalability_claim_allowed
    assert not audit.release_gate_allowed
