"""CUDA-Q parity matrix contract guard.

The contract is the source of truth and the published scoreboard is generated
from it, so these tests fail closed on both a contract violation and a stale
generated document.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

from flagquantum.runtime.audit.engine import audit_distributed_scalability
from tools.parity_matrix import (
    CONTRACT_PATH,
    MATURITY_PATH,
    OUTPUT_PATH,
    load_inputs,
    probe_problems,
    render_document,
    validate_contract,
    version_pin_problems,
)

pytestmark = pytest.mark.unit

ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture()
def contract_and_registry() -> tuple[dict, dict]:
    return load_inputs()


@pytest.fixture()
def contract(contract_and_registry: tuple[dict, dict]) -> dict:
    return copy.deepcopy(contract_and_registry[0])


def _first_row(contract: dict) -> dict:
    return contract["domains"][0]["capabilities"][0]


def test_parity_contract_is_valid(contract_and_registry: tuple[dict, dict]) -> None:
    assert validate_contract(*contract_and_registry) == []


def test_parity_contract_points_at_recorded_baseline(
    contract_and_registry: tuple[dict, dict],
) -> None:
    contract, _ = contract_and_registry
    instrument = contract["baseline"]["instrument"]
    assert (ROOT / instrument).is_file()


def test_generated_scoreboard_is_current(
    contract_and_registry: tuple[dict, dict],
) -> None:
    contract, _ = contract_and_registry
    assert OUTPUT_PATH.is_file(), "run tools/parity_matrix.py"
    assert OUTPUT_PATH.read_text(encoding="utf-8") == render_document(contract)


def test_generated_scoreboard_is_marked_generated() -> None:
    first_line = OUTPUT_PATH.read_text(encoding="utf-8").splitlines()[0]
    assert first_line.startswith("<!-- Generated by tools/parity_matrix.py")


def test_every_supported_row_names_a_registry_entry(contract: dict) -> None:
    for domain in contract["domains"]:
        for row in domain["capabilities"]:
            if row["status"] == "supported":
                assert row.get(
                    "maturity_ref"
                ), f"{row['id']} claims support with no registry entry"


def test_contract_rejects_unknown_status(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    _first_row(contract)["status"] = "strong"
    errors = validate_contract(contract, contract_and_registry[1])
    assert any("status is 'strong'" in error for error in errors)


def test_contract_rejects_unregistered_maturity_reference(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    _first_row(contract)["maturity_ref"] = "not_a_registered_capability"
    errors = validate_contract(contract, contract_and_registry[1])
    assert any(
        "is not declared in capability-maturity.toml" in error for error in errors
    )


def test_contract_rejects_a_supported_row_without_a_registry_entry(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    row = _first_row(contract)
    row["status"] = "supported"
    row.pop("maturity_ref", None)
    errors = validate_contract(contract, contract_and_registry[1])
    assert any("'supported' requires a maturity_ref" in error for error in errors)


def test_contract_rejects_a_missing_evidence_path(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    _first_row(contract)["evidence"] = ["flagquantum/does_not_exist.py"]
    errors = validate_contract(contract, contract_and_registry[1])
    assert any("evidence path does not exist" in error for error in errors)


def test_contract_rejects_an_unexplained_row(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    _first_row(contract).pop("reason", None)
    errors = validate_contract(contract, contract_and_registry[1])
    assert any("without a reason" in error for error in errors)


def test_contract_rejects_excluded_priority_without_out_of_scope_status(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    _first_row(contract)["priority"] = "excluded"
    errors = validate_contract(contract, contract_and_registry[1])
    assert any(
        "'excluded' priority requires 'out_of_scope' status" in error
        for error in errors
    )


def test_contract_rejects_a_domain_without_evidence(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    domain = contract["domains"][0]
    domain.pop("evidence", None)
    for row in domain["capabilities"]:
        row.pop("evidence", None)
    errors = validate_contract(contract, contract_and_registry[1])
    assert any(
        "no evidence, and the domain declares no default evidence" in error
        for error in errors
    )


def test_contract_rejects_a_reordered_domain_list(
    contract: dict, contract_and_registry: tuple[dict, dict]
) -> None:
    contract["domains"] = list(reversed(contract["domains"]))
    errors = validate_contract(contract, contract_and_registry[1])
    assert any("domain_order must list every" in error for error in errors)


def test_contract_and_registry_are_read_from_the_repository() -> None:
    assert CONTRACT_PATH == ROOT / "contracts" / "cudaq-parity-matrix.toml"
    assert MATURITY_PATH == ROOT / "capability-maturity.toml"


def test_cudaq_contracts_pin_the_same_versions(contract: dict) -> None:
    assert version_pin_problems(contract) == []


def test_version_pin_gate_rejects_drift_against_the_export_contract(
    contract: dict,
) -> None:
    contract["cudaq_versions"] = ["9.9.9"]
    errors = version_pin_problems(contract)
    assert any("must match contracts/cudaq-export-contract.toml" in e for e in errors)


def test_ci_gates_the_matrix_and_the_certified_cudaq_lane_agrees(
    contract: dict,
) -> None:
    workflow = (ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    assert "python tools/parity_matrix.py --check" in workflow
    pinned = " ".join(contract["cudaq_versions"])
    assert f'OPTIONAL_VERSIONS: "{pinned}"' in workflow


def _probe(contract: dict, path: str) -> dict:
    for probe in contract["baseline"]["probes"]:
        if probe["path"] == path:
            return probe
    raise AssertionError(f"the contract does not register {path}")


def test_a_measured_probe_must_name_a_landed_payload_and_its_report(
    contract: dict,
) -> None:
    probe = _probe(contract, "benchmarks/cudaq_backend_compare.py")
    assert probe["status"] == "measured"
    for field in ("payload", "report"):
        artifact = ROOT / probe[field]
        assert artifact.is_file(), f"{probe[field]} is registered but absent"


def test_contract_rejects_a_measured_probe_with_no_payload(contract: dict) -> None:
    probe = _probe(contract, "benchmarks/cudaq_backend_compare.py")
    probe.pop("payload")
    errors = probe_problems(contract)
    assert any(
        "status is 'measured' but no payload names the evidence" in error
        for error in errors
    )


def test_contract_rejects_a_measured_probe_pointing_at_a_missing_payload(
    contract: dict,
) -> None:
    _probe(contract, "benchmarks/cudaq_backend_compare.py")[
        "payload"
    ] = "benchmarks/results/comparison/not_recorded.json"
    errors = probe_problems(contract)
    assert any("the measured status rests on nothing" in error for error in errors)


def test_a_landed_payload_survives_the_benchmark_audit() -> None:
    probe = _probe(load_inputs()[0], "benchmarks/cudaq_backend_compare.py")
    payload = json.loads((ROOT / probe["payload"]).read_text(encoding="utf-8"))
    audit = audit_distributed_scalability(payload)
    assert audit.valid, audit.summary()
    assert not audit.scalability_claim_allowed
    assert not audit.release_gate_allowed
