"""Versioned, isolated extension SDK outside the stable root API."""

from .conformance import (
    ConformanceReport,
    check_manifest_serialization,
    run_backend_conformance,
    run_provider_conformance,
)
from .sdk import (
    SDK_API_VERSION,
    CapabilityRequest,
    CapabilityResponse,
    CompilerPassExtension,
    DeviceExtension,
    ExecutionBackendExtension,
    ExtensionCompatibilityError,
    ExtensionConfig,
    ExtensionError,
    ExtensionHandle,
    ExtensionLifecycleError,
    ExtensionManifest,
    ExtensionRegistry,
    KernelExtension,
    MeasurementCollectorExtension,
    OperatorExtension,
    PlannerExtension,
    ProviderExtension,
    extension_scope,
)

__all__ = (
    "SDK_API_VERSION",
    "CapabilityRequest",
    "CapabilityResponse",
    "ConformanceReport",
    "CompilerPassExtension",
    "DeviceExtension",
    "ExecutionBackendExtension",
    "ExtensionCompatibilityError",
    "ExtensionConfig",
    "ExtensionError",
    "ExtensionHandle",
    "ExtensionLifecycleError",
    "ExtensionManifest",
    "ExtensionRegistry",
    "KernelExtension",
    "MeasurementCollectorExtension",
    "OperatorExtension",
    "PlannerExtension",
    "ProviderExtension",
    "extension_scope",
    "check_manifest_serialization",
    "run_backend_conformance",
    "run_provider_conformance",
)
